// rcdata.h - chat.rc's resources as linked-in data.
//
// The original compiled chat.rc with rc.exe and the linker put the result in the .exe's
// resource section; the engine reads it back through FindResource/LockResource and
// LoadString. A Mach-O binary has no resource section, so the same bytes are compiled in as
// static arrays instead (native/shim/rcdata.cpp, generated by native/gen-rcdata.py) and the
// resource API is served from those. The engine's own calls are untouched.
//
// Consequences worth stating, because they are the reason this is not a data file:
//   * nothing to ship, nothing to lose from a bundle, nothing to parse at startup
//   * FindResource returns a pointer into static storage, which is what LockResource did -
//     dib.cpp's "not required to unlock or free the resource in Win32" stays true
//   * a missing resource is a build-time problem, visible when the generator runs, rather
//     than a blank pane at runtime

#ifndef NATIVE_SHIM_RCDATA_H
#define NATIVE_SHIM_RCDATA_H

// One STRINGTABLE entry. `text` may contain embedded NULs in principle; the engine's
// LoadString callers treat it as a C string, as MFC's do.
struct NativeRcString {
    unsigned int id;
    const char*  text;
};

// One BITMAP, DIB or ICON: the file's bytes verbatim, header included.
struct NativeRcBinary {
    unsigned int         id;
    const char*          type;      // "BITMAP", "DIB", "ICON"
    const char*          name;      // the RC symbol, for diagnostics
    const unsigned char* data;
    unsigned long        size;
};

extern const NativeRcString kNativeRcStrings[];
extern const int            kNativeRcStringCount;
extern const NativeRcBinary kNativeRcBinaries[];
extern const int            kNativeRcBinaryCount;

#endif // NATIVE_SHIM_RCDATA_H
