#!/usr/bin/env python3
"""Extract chat.rc's STRINGTABLE entries into native/resources/strings.json.

A Mach-O binary has no PE resource section, but the engine reads real behaviour out of
the string table - not just UI labels. textpose.cpp's InitializeEmotionRules loads the
emotion-detection RULES from it (ID_RULE_SHOUT and friends), so without these the native
build has no emotion rules at all and every pose decision differs from the goldens.
That is why this is generated data rather than a stub returning FALSE.

There is a natural check on this extractor: with the strings loaded, the native
--textpose dump must reproduce oracle/textpose/textpose.golden.json, which was captured
on Windows from the real resource table. If the parse mangles an escape, the rules
differ and that diff fails.

RC string syntax handled:
  * outer double quotes delimit; "" inside means a literal quote
  * C escapes \\n \\t \\r \\\\ \\" and \\ooo octal
  * adjacent string literals on one line concatenate
  * a trailing backslash or an unterminated line continues onto the next
"""
import json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TREE = os.path.join(ROOT, 'v2.5-beta-1-modern')

def parse_resource_h(path):
    """name -> numeric id, following simple #define chains."""
    ids = {}
    pat = re.compile(r'^\s*#define\s+([A-Za-z_]\w*)\s+(.+?)\s*$')
    for line in open(path, encoding='latin-1'):
        m = pat.match(line)
        if not m:
            continue
        name, val = m.group(1), m.group(2).split('//')[0].split('/*')[0].strip()
        if re.fullmatch(r'0[xX][0-9a-fA-F]+', val):
            ids[name] = int(val, 16)
        elif re.fullmatch(r'-?\d+', val):
            ids[name] = int(val)
        elif val in ids:
            ids[name] = ids[val]
    return ids

def unescape_rc(body):
    """Turn an RC string literal body into its runtime bytes."""
    out = []
    i = 0
    while i < len(body):
        c = body[i]
        if c == '"' and i + 1 < len(body) and body[i + 1] == '"':
            out.append('"'); i += 2; continue
        if c == '\\' and i + 1 < len(body):
            n = body[i + 1]
            simple = {'n': '\n', 't': '\t', 'r': '\r', '\\': '\\', '"': '"', 'a': '\a', '0': '\0'}
            if n in simple:
                out.append(simple[n]); i += 2; continue
            m = re.match(r'\\([0-7]{1,3})', body[i:])
            if m:
                out.append(chr(int(m.group(1), 8))); i += len(m.group(0)); continue
            # Unknown escape: RC passes the character through.
            out.append(n); i += 2; continue
        out.append(c); i += 1
    return ''.join(out)

def extract_stringtables(path, ids):
    """(id, text) for every STRINGTABLE entry, resolving names through resource.h."""
    text = open(path, encoding='latin-1').read()
    lines = text.split('\n')
    entries = {}
    unresolved = []
    i = 0
    while i < len(lines):
        if not re.match(r'^\s*STRINGTABLE\b', lines[i]):
            i += 1; continue
        # Skip to BEGIN (or '{'), then read until END (or '}').
        i += 1
        while i < len(lines) and not re.match(r'^\s*(BEGIN|\{)\s*$', lines[i]):
            i += 1
        i += 1
        while i < len(lines) and not re.match(r'^\s*(END|\})\s*$', lines[i]):
            raw = lines[i]
            # An entry is: IDENT (or number) followed by one or more string literals.
            m = re.match(r'^\s*([A-Za-z_]\w*|\d+)\s+(.*)$', raw)
            if not m:
                i += 1; continue
            key, rest = m.group(1), m.group(2)
            # Gather literals, following continuation lines while quotes are unbalanced.
            buf = rest
            while buf.count('"') % 2 == 1 and i + 1 < len(lines):
                i += 1
                buf += '\n' + lines[i].strip()
            parts = re.findall(r'"((?:[^"]|"")*)"', buf)
            if not parts:
                i += 1; continue
            value = ''.join(unescape_rc(p) for p in parts)
            if re.fullmatch(r'\d+', key):
                entries[int(key)] = value
            elif key in ids:
                entries[ids[key]] = value
            else:
                unresolved.append(key)
            i += 1
        i += 1
    return entries, unresolved

def main():
    ids = parse_resource_h(os.path.join(TREE, 'resource.h'))
    entries, unresolved = extract_stringtables(os.path.join(TREE, 'chat.rc'), ids)

    outdir = os.path.join(ROOT, 'native', 'resources')
    os.makedirs(outdir, exist_ok=True)
    out = {
        '_comment': 'GENERATED by native/gen-strings.py from v2.5-beta-1-modern/chat.rc. '
                    'Do not hand-edit. The engine reads BEHAVIOUR from these, not just '
                    'labels - textpose.cpp loads its emotion-detection rules here.',
        'strings': {str(k): v for k, v in sorted(entries.items())},
    }
    path = os.path.join(outdir, 'strings.json')
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(out, f, indent=1, ensure_ascii=False, sort_keys=False)
        f.write('\n')

    print(f"wrote {os.path.relpath(path, ROOT)}: {len(entries)} strings"
          f"{f', {len(set(unresolved))} unresolved names' if unresolved else ''}")

    # Show the emotion rules, since they are the load-bearing ones and the easiest to
    # eyeball for a mangled escape.
    for name in ('ID_RULE_SHOUT', 'ID_RULE_HAPPY', 'ID_EM_HAPPY'):
        if name in ids and ids[name] in entries:
            print(f"  {name} = {entries[ids[name]]!r}")

if __name__ == '__main__':
    main()
