#!/usr/bin/env python3
"""Generate native/uistubs.cpp from the linker's undefined-symbol list.

Run after a failed link:
    clang++ -o /dev/null <objs> 2>&1 | ... > /tmp/undef.txt
    python3 native/gen-uistubs.py

Why generated rather than hand-written: the declarations live in engine headers, but
Itanium-mangled names carry no return type, so definitions cannot be derived from the
linker's output alone. Defining each symbol under its exact mangled name via an asm
label sidesteps that - the linker matches by name and never sees a signature.

Two things that cost a round each and are easy to get wrong again:

  * The definitions must have EXTERNAL linkage. In an anonymous namespace the asm label
    decorates an internal symbol and defines nothing the linker can use.
  * clang uses an explicit __asm__("name") label VERBATIM - it does not prepend the
    platform underscore. So the label must be the full symbol as `nm` prints it,
    including its leading underscore.
"""
import json, subprocess, sys

targets = json.load(open('/tmp/targets.json'))
# There used to be a special case appending _serverConn unconditionally, from when it was
# referenced but nothing defined it. ircproto.cpp now compiles and defines it for real, so
# appending it here produced a duplicate symbol. Removed rather than made conditional:
# targets.json comes straight from the linker, so anything genuinely missing is already
# in it, and a hand-maintained addition can only go stale the same way this one did.

# Classifying a symbol as function-or-data by "does the demangled name have parentheses"
# works for C++ but is WRONG for C: a C name does not demangle, so it never has parens and
# every C function was being emitted as a zeroed data blob. Calling one then jumps into
# zeroed memory and dies as EXC_BAD_ACCESS with no usable backtrace - which is exactly how
# GetMime() presented, and it cost a real debugging session.
#
# There is no way to tell a C function from a C global by name, so they are listed
# explicitly and an unknown one is a hard error rather than a guess. Failing loudly is the
# whole point: a silent misclassification is far more expensive than adding a line here.
C_DATA = {
    '_g_hinstMSConf',    # extern HINSTANCE (NetMeeting module handle)
    '_g_hinstRatings',   # extern HINSTANCE (content-ratings module handle)
    '_serverConn',
}
C_FUNCS = {
    '_ConferenceConnectA', '_ConferenceGetInfoA', '_ConferenceListen',
    '_FindSubStringForINTLThatFits',   # intl.c; unreachable while GetMime() is NULL
    '_GetMime',
}

def classify(m, d):
    if m.startswith('__ZTV'):
        return 'vtable'
    if m.startswith('__Z'):                       # C++: parens are reliable
        return 'func' if '(' in d else 'data'
    if m in C_DATA:
        return 'data'
    if m in C_FUNCS:
        return 'func'
    raise SystemExit(
        f"gen-uistubs: {m} ({d}) is not a C++ symbol and is in neither C_DATA nor\n"
        f"  C_FUNCS. Classify it explicitly - guessing produces either a data blob that\n"
        f"  crashes when called, or a function whose bytes get read as a value.")

kinds   = [(m, d, classify(m, d)) for m, d in targets]
vtables = [(m, d) for m, d, k in kinds if k == 'vtable']
data    = [(m, d) for m, d, k in kinds if k == 'data']
funcs   = [(m, d) for m, d, k in kinds if k == 'func']

HEADER = '''// uistubs.cpp - GENERATED by native/gen-uistubs.py. Do not hand-edit.
//
// Definitions for every symbol the corpus replay references but the native build does
// not provide: MFC dialogs and property pages, the rules and notifications engine,
// NetMeeting, sound, the CJK/INTL path, and a handful of globals. None of it is engine
// geometry, layout or asset handling - all of that compiles and links for real.
//
// EVERY FUNCTION ABORTS, and that is the point. The corpus replay is not supposed to
// open a dialog, drive the rules engine or play a sound. If it reaches one of these the
// resulting dump would be wrong, so a stack trace naming the symbol is exactly what is
// wanted; a silent no-op would instead surface later as an inexplicable golden
// mismatch.
//
// Vtables are arrays of pointers to one aborting function, so a virtual call through a
// stubbed vtable aborts rather than jumping into arbitrary data.
//
// Data symbols are zeroed storage. A READ of one is NOT caught - that is the weak spot
// in this file, and the reason these want replacing with real AppKit implementations
// rather than being lived with.

#include <stdio.h>
#include <stdlib.h>

extern "C" void NativeUiStubAbort(const char* what) {
    fprintf(stderr, "\\nnative: reached UI/subsystem stub '%s'\\n"
                    "  The corpus replay should not need this. Either the replay is doing\\n"
                    "  something it should not, or this symbol belongs in the real port.\\n", what);
    abort();
}

// External linkage and the verbatim mangled label - see the module comment.
'''

out = [HEADER]
for i, (m, d) in enumerate(funcs):
    esc = d.replace('\\', '\\\\').replace('"', '\\"')
    out.append(f'__attribute__((used)) void stub_f{i}() __asm__("{m}");\n'
               f'__attribute__((used)) void stub_f{i}() {{ NativeUiStubAbort("{esc}"); }}\n')

out.append('\n__attribute__((used)) void stub_vcall() '
           '{ NativeUiStubAbort("virtual call through a stubbed vtable"); }\n'
           'typedef void (*VFn)();\n')
for i, (m, d) in enumerate(vtables):
    esc = d.replace('"', '\\"')
    slots = ', '.join(['stub_vcall'] * 64)
    out.append(f'// {esc}\n__attribute__((used)) VFn stub_vt{i}[64] __asm__("{m}") = {{\n    {slots}\n}};\n')

out.append('\n// Zeroed storage, oversized on purpose: a too-small guess would let a write\n'
           '// corrupt the next symbol.\n')
for i, (m, d) in enumerate(data):
    esc = d.replace('"', '\\"')
    out.append(f'// {esc}\n__attribute__((used)) alignas(16) char stub_d{i}[4096] __asm__("{m}");\n')

open('native/uistubs.cpp', 'w').write(''.join(out))
print(f"wrote native/uistubs.cpp: {len(funcs)} functions, {len(vtables)} vtables, {len(data)} data")
