// oracleharness.cpp - C++ console oracle harness for Comic Chat v2.5-beta-1-modern.
//
// Links the real engine .obj files + static MFC, supplies a stub theApp/cui
// with a desktop CClientDC (MM_TWIPS), and replays scripted message sequences
// through CChatDoc::ProcessLine -> CUnitPanelPage::AddLine, then dumps the
// Tier-3 engine state as expected.json.
//
// Build: nmake /f oracle.mak CFG="oracle - Win32 Release"
//   (called from the v2.5-beta-1-modern directory with ORACLE=1)
//
// Usage: OracleHarness.exe <inputs.json> <expected.json>
//        OracleHarness.exe --glyphs <glyphs.json>
//        OracleHarness.exe --codecs <codecs.json>
//        OracleHarness.exe --ccc <ccc.json> [treeDir]
//        OracleHarness.exe --avb <outDir> [artDir]
//
// See oracle/harness/README.md for the linkage design decision.

#include "stdafx.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <string>
#include <vector>
#include <algorithm>   // std::sort, for the deterministic ComicArt asset order

#include "chat.h"
#include "bbox.h"
#include "traj.h"
#include "spline.h"
#include "pe.h"
#include "dib.h"
#include "avatar.h"
#include "avatario.h"
#include "balloon.h"
#include "backdrop.h"
#include "pageview.h"
#include "panel.h"
#include "ui.h"
#include "vector2d.h"
#include "format.h"
#include "protsupp.h"
#include "userinfo.h"
#include "chatprot.h"
#include "binddoc.h"
#include "chatdoc.h"
#include "histent.h"
// Tier-1 codec dumps (--codecs): mode maps live in protsupp.h, the formatting
// codec in artifacts/inc/format.h (already included above), ParseIt/FreeParse
// in ircsock.h, CDosKey in doskey.h, and CUrlRec in artifacts/inc/urlutil.h.
#include "ircsock.h"
#include "doskey.h"
#include "urlutil.h"

#include "ojson.h"
#include "oracleseed.h"

// Stubs for COM type library symbols normally generated by MIDL from
// base/icchat.idl. The harness doesn't use OLE automation, but chat.obj
// and bindauto.obj reference these globals.
#include "icchat.h"
EXTERN_C const IID LIBID_iCChatLib = GUID_NULL;
EXTERN_C const IID IID_ICChatAutomation = GUID_NULL;

// We link against the real engine objs which define these:
extern CChatApp theApp;
extern CUI cui;

// Globals from the engine we need:
extern void LoadEmotionStrings();
extern void InitializeEmotionRules();
extern void InitializeBackDrops();
extern int GetCurrentBackDropID();
extern void SetArtDir(const char *);
extern void InitializeAvatars();
extern CAvatarX *LoadAvatar(const char *avName);
extern CAvatarX *GetAvatar(USHORT avatarID);
extern double randfloat();
extern void GetEmotionsFromString(CString &str, CEmotionOpts &emOpts);
// avatario.cpp: EmotionToBytes/BytesToEmotion are forward-declared locally
// in avatario.cpp:66-67 (NOT in avatario.h) — repeat them here for the
// CaptureAvatario dump.
extern void EmotionToBytes(CEmotion &em, BYTE &emotion, BYTE &intensity);
extern void BytesToEmotion(CEmotion &em, BYTE emIndex, BYTE inIndex);
// format.cpp:20 owns the single CUrlRec instance; the --codecs dump drives the
// live URL detector through it (Tier-1 #8).
extern CUrlRec g_urlRec;

// CChatDoc has a protected ctor + DECLARE_DYNCREATE; we need to construct
// it. The MFC runtime class is accessible via the doc template machinery,
// but in a console harness we bypass that. We friend-access via a helper.
// Since CChatDoc() is protected and DECLARE_DYNCREATE'd, we use the
// CRuntimeClass::CreateObject path which MFC provides.
// Actually, the simplest approach: we declare a public-ctor subclass
// right here, but CChatDoc's dtor and key methods are public, so we just
// need to get past the protected ctor. We use a one-line shim.

// The MFC CRuntimeClass for CChatDoc is exported by DECLARE_DYNCREATE.
// We access it via RUNTIME_CLASS(CChatDoc) which requires the class to
// be in the MFC runtime chain. Since we link the real chatdoc.obj,
// IMPLEMENT_DYNCREATE(CChatDoc, CDocObjectServerDoc) is in the image.
// But CDocObjectServerDoc needs OLE init... Let's try constructing
// directly via a friend hack.

// Friend hack: CChatDoc has a protected constructor. We create a
// minimal subclass with a public constructor that calls the base.
// This works because CChatDoc's constructor is protected, not private,
// and MFC DECLARE_DYNCREATE makes the runtime class available.
class COracleChatDoc : public CChatDoc {
public:
    COracleChatDoc() : CChatDoc() {}
};

// We need a stub CChatView whose GetDocument() returns our doc.
// The engine's SayEntry::Execute calls GetView()->GetDocument(), but
// we don't use ExecuteHistory -- we call ProcessLine directly.
// GetChatDoc() macro -> cui.GetChatDocPv() -> cui.m_pvChatDoc
// We set cui.m_pvChatDoc to our doc.

// ---------------------------------------------------------------------------
// Stub CWinApp: we need theApp to exist as a global (it's defined in
// chat.cpp), but CWinApp normally requires InitInstance. We don't call
// theApp.InitInstance() -- we call the individual init functions
// directly. However, CWinApp's constructor does some MFC internal
// registration that requires AfxWinInit. We call AfxWinInit manually.
// ---------------------------------------------------------------------------

// Forward declarations of init functions we call directly
extern "C" BYTE GetCorrectCharSet();
extern int PointsToTwips(int);

static int g_screenDpi = 96;

// ---------------------------------------------------------------------------
// Glyph capture: dump advance widths + CFontInfo scalars
// ---------------------------------------------------------------------------
// ---------------------------------------------------------------------------
// Glyph capture.
//
// Captures EVERY font the engine creates, not just the balloon font. fonts.cpp makes
// four per page - balloon, whisper (italic), title and shout - and UpdateTitleFonts
// scales the last two by m_unitWidth/4860, so the set depends on panel width:
//
//   nFontHeightTitle = -576, nFontHeightShout = -252 (defines.h:137-138), each
//   multiplied by the reduction and then clamped against m_iFontHeightBalloon:
//     title = min((int)(-576 * r), (int)(1.2 * balloonHeight))
//     shout = min((int)(-252 * r), balloonHeight)
//
// At the corpus's two panel widths (4860 -> r = 1.0, and 2300 for case 014) that gives
// title -576 / shout -252, and title -288 / shout -240 respectively. The whisper font is
// the balloon size in ITALIC, which has different advances entirely.
//
// This matters because the native port measures from this table and REFUSES to measure
// a font it does not cover - which is how the omission was found: the corpus replay
// aborted naming lfHeight -576. A table with only the balloon font cannot reproduce any
// golden that draws a title or a shout.
//
// Emits both shapes: the top-level `font` object stays exactly as it was (the TS port
// and RULEBOOK 5 consume it, and the balloon font is what they need), plus a `fonts`
// array carrying all five keyed by lfHeight and lfItalic.
// ---------------------------------------------------------------------------

// The probe strings for the sum-of-advances check. See CaptureOneFont.
static const char* kExtentProbes[] = {
    "AV", "To", "Yo", "WA", "f.", "il", "mm", "MMM",
    "   ", "the quick brown fox", "Hello, world!",
    "caf\xE9", "na\xEFve", "\xFC" "ber",
    "...", "!!!", "1234567890",
    NULL
};

// Captures one font: its TEXTMETRIC scalars, the 0x20-0xFF advances, and the extent
// probes. cFontInfo is only meaningful for the balloon font (the engine derives the
// other CFontInfos with different leading/baseAdd), so it is emitted separately by the
// caller rather than here.
static ojson::Value CaptureOneFont(CDC& dc, int lfHeight, BOOL italic, const char* role) {
    LOGFONT lf;
    memset(&lf, 0, sizeof(lf));
    lf.lfHeight = lfHeight;
    lf.lfWidth = 0;
    lf.lfWeight = FW_NORMAL;
    lf.lfItalic = (BYTE)(italic ? TRUE : FALSE);
    lf.lfUnderline = FALSE;
    lf.lfStrikeOut = FALSE;
    lf.lfCharSet = ANSI_CHARSET;
    lf.lfOutPrecision = OUT_DEFAULT_PRECIS;
    lf.lfClipPrecision = CLIP_DEFAULT_PRECIS;
    lf.lfQuality = DEFAULT_QUALITY;
    lf.lfPitchAndFamily = DEFAULT_PITCH | FF_DONTCARE;
    strcpy(lf.lfFaceName, "Comic Sans MS");

    CFont font;
    font.CreateFontIndirect(&lf);
    CFont* pOld = dc.SelectObject(&font);

    TEXTMETRIC tm;
    dc.GetTextMetrics(&tm);

    ojson::Value v = ojson::Value::Obj();
    v.Set("role", ojson::Value::Str(role));
    v.Set("faceName", ojson::Value::Str("Comic Sans MS"));
    v.Set("lfHeight", ojson::Value::Int(lfHeight));
    v.Set("lfItalic", ojson::Value::Int(italic ? 1 : 0));
    v.Set("tmHeight", ojson::Value::Int(tm.tmHeight));
    v.Set("tmAscent", ojson::Value::Int(tm.tmAscent));
    v.Set("tmDescent", ojson::Value::Int(tm.tmDescent));
    v.Set("tmInternalLeading", ojson::Value::Int(tm.tmInternalLeading));
    v.Set("tmExternalLeading", ojson::Value::Int(tm.tmExternalLeading));
    v.Set("tmAveCharWidth", ojson::Value::Int(tm.tmAveCharWidth));
    v.Set("tmMaxCharWidth", ojson::Value::Int(tm.tmMaxCharWidth));
    v.Set("tmOverhang", ojson::Value::Int(tm.tmOverhang));
    // tmCharSet is captured because fonts.cpp branches on it: the whisper font is
    // italicised only when tmCharSet < 3 or is one of the European sets, so a port that
    // guessed it wrong would italicise the wrong balloons.
    v.Set("tmCharSet", ojson::Value::Int(tm.tmCharSet));

    ojson::Value advances = ojson::Value::Arr();
    for (int c = 0x20; c <= 0xFF; c++) {
        char ch[2] = { (char)c, 0 };
        CSize ext = dc.GetTextExtent(ch, 1);
        ojson::Value e = ojson::Value::Obj();
        e.Set("char", ojson::Value::Int(c));
        e.Set("advance", ojson::Value::Int(ext.cx));
        advances.Push(e);
    }
    v.Set("glyphAdvances", advances);

    ojson::Value probes = ojson::Value::Arr();
    for (int i = 0; kExtentProbes[i] != NULL; i++) {
        int len = (int)strlen(kExtentProbes[i]);
        CSize ext = dc.GetTextExtent(kExtentProbes[i], len);
        ojson::Value e = ojson::Value::Obj();
        e.Set("text", ojson::Value::Str(kExtentProbes[i]));
        e.Set("length", ojson::Value::Int(len));
        e.Set("width", ojson::Value::Int(ext.cx));
        e.Set("height", ojson::Value::Int(ext.cy));
        probes.Push(e);
    }
    v.Set("extentProbes", probes);

    dc.SelectObject(pOld);
    return v;
}

static ojson::Value CaptureGlyphs() {
    ojson::Value root = ojson::Value::Obj();

    // Desktop DC with MM_TWIPS, same as pageview.cpp:994
    CClientDC dc(CWnd::FromHandle(::GetDesktopWindow()));
    dc.SetMapMode(MM_TWIPS);

    // The balloon font: Comic Sans MS at the default balloon size.
    // chat.cpp:381 m_iFontHeightBalloon = PointsToTwips(atoi(strDefaultFontHeight)),
    // IDS_DFLT_COMICSPNTSIZE = "12" (chat.rc:2336).
    int balloonHeight = PointsToTwips(12);

    // --- the legacy top-level `font` object, unchanged in shape --------------------
    // Kept byte-compatible because RULEBOOK 5 and the TS port read it directly; the
    // `fonts` array below is additive.
    ojson::Value fontInfo = CaptureOneFont(dc, balloonHeight, FALSE, "balloon");
    fontInfo.Set("role", ojson::Value::Null());   // absent from the legacy shape
    {
        // Re-select for the CFontInfo scalars, which are derived rather than measured.
        LOGFONT lf;
        memset(&lf, 0, sizeof(lf));
        lf.lfHeight = balloonHeight;
        lf.lfWeight = FW_NORMAL;
        lf.lfCharSet = ANSI_CHARSET;
        lf.lfOutPrecision = OUT_DEFAULT_PRECIS;
        lf.lfClipPrecision = CLIP_DEFAULT_PRECIS;
        lf.lfQuality = DEFAULT_QUALITY;
        lf.lfPitchAndFamily = DEFAULT_PITCH | FF_DONTCARE;
        strcpy(lf.lfFaceName, "Comic Sans MS");
        CFont font;
        font.CreateFontIndirect(&lf);
        CFont* pOld = dc.SelectObject(&font);
        TEXTMETRIC tm;
        dc.GetTextMetrics(&tm);

        // CFontInfo scalars (balloon.h:47, fonts.cpp:89)
        double reduction = (double)abs(lf.lfHeight) / 180.0;
        int doVKern = 1;   // Comic Sans MS
        short leading = (short)(-40 * reduction * doVKern);
        short baseAdd = (short)(30 * reduction * doVKern);
        CSize contExt = dc.GetTextExtent("...", 3);

        ojson::Value cfi = ojson::Value::Obj();
        cfi.Set("m_leading", ojson::Value::Int(leading));
        cfi.Set("m_baseAdd", ojson::Value::Int(baseAdd));
        cfi.Set("m_lineHeight", ojson::Value::Int((short)(tm.tmHeight + leading)));
        cfi.Set("m_continuationWidth", ojson::Value::Int((short)contExt.cx));
        cfi.Set("m_topOffset", ojson::Value::Int((short)(tm.tmAscent + leading + baseAdd)));
        fontInfo.Set("cFontInfo", cfi);
        dc.SelectObject(pOld);
    }
    root.Set("font", fontInfo);

    // --- every font the engine actually creates -----------------------------------
    // Heights derived exactly as UpdateTitleFonts does, for both panel widths the
    // corpus uses, so the set is complete for the corpus rather than guessed.
    ojson::Value fonts = ojson::Value::Arr();
    fonts.Push(CaptureOneFont(dc, balloonHeight, FALSE, "balloon"));
    fonts.Push(CaptureOneFont(dc, balloonHeight, TRUE,  "whisper"));

    static const int kPanelWidths[] = { 4860, 2300 };   // 2300 is corpus case 014
    for (int i = 0; i < 2; i++) {
        float r = (float)kPanelWidths[i] / 4860;
        int titleH = (int)(nFontHeightTitle * r);
        titleH = min(titleH, (int)(1.2 * balloonHeight));
        int shoutH = (int)(nFontHeightShout * r);
        shoutH = min(shoutH, balloonHeight);

        char role[64];
        snprintf(role, sizeof(role), "title@%d", kPanelWidths[i]);
        fonts.Push(CaptureOneFont(dc, titleH, FALSE, role));
        snprintf(role, sizeof(role), "shout@%d", kPanelWidths[i]);
        fonts.Push(CaptureOneFont(dc, shoutH, FALSE, role));
    }
    root.Set("fonts", fonts);

    root.Set("dpi", ojson::Value::Int(g_screenDpi));
    root.Set("mapMode", ojson::Value::Str("MM_TWIPS"));
    return root;
}

// ---------------------------------------------------------------------------
// CaptureTextpose — Tier-1 #1 dump: run a fixed battery of probe strings
// through GetEmotionsFromString and emit the CEmotionOpts results. This gives
// the TS textpose port a real oracle golden to diff against (closing the gap
// noted in the Phase-4 textpose port, where only hand-computed goldens existed).
//
// The battery covers each rule family: AllCaps, FindString (case-sens/insens),
// CheckWord, CheckStart, multi-rule interaction, dedup, and negative cases.
// Each entry: { "text": "...", "opts": [ {emotion, intensity, priority}, ... ] }.
// ---------------------------------------------------------------------------
static ojson::Value CaptureTextpose() {
    // Probe battery. Keep in sync with port/test/engine/textpose.test.ts cases
    // so the TS golden test can consume this dump directly.
    const char* probes[] = {
        "HELLO",                    // AllCaps -> SHOUT
        "what!!!",                  // FindString("!!!") -> SHOUT
        "hello",                    // no SHOUT (lowercase)
        "that is LOL",              // CheckWord* LOL -> LAUGH
        "that is lol",              // case-insensitive LOL -> LAUGH
        "ROTFL",                    // CheckWord* ROTFL -> LAUGH
        "hehe that's great",        // FindString* HEHE -> LAUGH
        "xLOL",                     // mid-word, no LAUGH
        "hi :)",                    // FindString :) -> HAPPY
        ":-) nice",                 // FindString :-) -> HAPPY
        "oh :( sad",               // FindString :( -> SAD
        ":-( bummer",              // FindString :-( -> SAD
        ";-) maybe",               // FindString ;-) -> COY
        ";) sure",                  // FindString ;) -> COY
        "Hello there",             // CheckStart* Hello -> WAVE
        "Hi",                       // CheckStart* Hi -> WAVE
        "Howdy partner",           // CheckStart* Howdy -> WAVE
        "Bye now",                  // CheckStart* Bye -> WAVE
        "Welcome",                  // CheckStart* Welcome -> WAVE
        "hello there",             // case-insensitive -> WAVE
        "Hellothere",              // no boundary after -> no WAVE
        "Well. Hello there",       // second-sentence Hello -> WAVE
        "I think so",              // CheckStart* I -> POINTSELF
        "I'm going",               // CheckStart* I + CheckWord* i'm -> POINTSELF (prio 7)
        "i am here",               // CheckWord* i am -> POINTSELF
        "You are nice",            // CheckStart* You -> POINTOTHER
        "how are you",             // CheckWord* are you -> POINTOTHER (prio 8)
        "will you go",             // CheckWord* will you -> POINTOTHER
        "Hello LOL :)",            // multi-rule: WAVE + LAUGH + HAPPY
        "I'm sure",                // dedup: POINTSELF prio 7 wins over 3
        "the quick brown fox jumps", // no triggers
        "",                        // empty
    };
    int nProbes = sizeof(probes) / sizeof(probes[0]);

    ojson::Value root = ojson::Value::Obj();
    ojson::Value cases = ojson::Value::Arr();
    for (int i = 0; i < nProbes; i++) {
        CString str(probes[i]);
        CEmotionOpts emOpts;
        GetEmotionsFromString(str, emOpts);

        ojson::Value entry = ojson::Value::Obj();
        entry.Set("text", ojson::Value::Str(probes[i]));
        ojson::Value optsArr = ojson::Value::Arr();
        for (int j = 0; j < emOpts.m_nOpts; j++) {
            ojson::Value opt = ojson::Value::Obj();
            // Emit emotion as a double (the emotion-wheel values are floats;
            // the special emotions are 1001/1002/1003). ojson doesn't have a
            // double emitter, so we emit via Str with full precision.
            char buf[64];
            sprintf(buf, "%.17g", (double)emOpts.m_emotions[j].m_emotion);
            opt.Set("emotion", ojson::Value::Str(buf));
            sprintf(buf, "%.17g", (double)emOpts.m_emotions[j].m_intensity);
            opt.Set("intensity", ojson::Value::Str(buf));
            opt.Set("priority", ojson::Value::Int(emOpts.m_priorities[j]));
            optsArr.Push(opt);
        }
        entry.Set("opts", optsArr);
        cases.Push(entry);
    }
    root.Set("probes", cases);
    return root;
}

// The Tier-1 avatario (#3) and avatar-pose (#2) dumps live in posedump.cpp, not
// here - shared with the NATIVE macOS build (native/posemain.cpp) for the same
// reason as avbdump.cpp: one implementation on two platforms makes a golden match
// attributable to the platform layer rather than to two dumps agreeing.
#include "posedump.h"


// ---------------------------------------------------------------------------
// Tier-1 stateless codecs (--codecs): #9 mode maps, #7 formatting codec,
// #6 IRC line parse, #12 CDosKey ring buffer, #8 URL detection.
//
// These share one dump because they share a shape: pure function in, bytes
// out, no document or avatar state. Nothing here allocates that the process
// needs back - the harness is one-shot, so returned buffers are left for exit
// to reclaim rather than guessing at each function's ownership contract.
//
// #8 is aimed at CUrlRec::HrIdentifyUrls, NOT at the plan's FIsURL/
// IHexToInteger: urlfind.cpp is absent from both chat.mak and oracle.mak, so
// that code is dead in the shipped client and its ||-vs-&& bug must not be
// reproduced. The live path is artifacts-modern/core/urlutil.cpp via the
// v2.5-beta-1-modern/urlutil.cpp shim, called from IdentifyURLs
// (format.cpp:1221).
// ---------------------------------------------------------------------------

// Escape a byte string for the dump. Control characters are the *point* of the
// formatting codec, so they must survive the round trip legibly; ojson emits
// bytes < 0x20 as \u00xx and rejects escapes above 0xFF on parse, which suits a
// byte-oriented corpus.
static ojson::Value CodecStr(const char* s) {
    return ojson::Value::Str(s ? s : "");
}

static ojson::Value DumpFormattingArray(CDWordArray& rgdw) {
    // Element layout per format.cpp:305 - HIWORD is the offset of the first
    // character, LOWORD the format word (effects | fg | bg).
    ojson::Value arr = ojson::Value::Arr();
    for (int i = 0; i < rgdw.GetSize(); i++) {
        DWORD dw = rgdw[i];
        ojson::Value e = ojson::Value::Obj();
        e.Set("raw", ojson::Value::Int((long)dw));
        e.Set("offset", ojson::Value::Int((long)HIWORD(dw)));
        e.Set("format", ojson::Value::Int((long)LOWORD(dw)));
        arr.Push(e);
    }
    return arr;
}

static ojson::Value CaptureCodecs() {
    ojson::Value root = ojson::Value::Obj();

    // --- Tier-1 #9: mode maps -------------------------------------------
    // Every byte for the index maps; the documented mode values plus the
    // combinations MakeBalloon accepts for SM2BM/BM2SM. BM2SM's argument is a
    // bit set, so the combined ACTION forms matter.
    {
        fprintf(stderr, "ORACLE: codecs - modeMaps\n"); fflush(stderr);
        ojson::Value mm = ojson::Value::Obj();
        ojson::Value i2b = ojson::Value::Arr(), b2i = ojson::Value::Arr();
        for (int i = 0; i < 256; i++) {
            i2b.Push(ojson::Value::Int((long)IndexToByte((BYTE)i)));
            b2i.Push(ojson::Value::Int((long)ByteToIndex((BYTE)i)));
        }
        mm.Set("indexToByte", i2b);
        mm.Set("byteToIndex", b2i);

        ojson::Value sm2bm = ojson::Value::Arr();
        for (int sm = 0; sm <= 8; sm++) {
            ojson::Value e = ojson::Value::Obj();
            e.Set("in", ojson::Value::Int((long)sm));
            e.Set("out", ojson::Value::Int((long)SM2BM((BYTE)sm)));
            sm2bm.Push(e);
        }
        mm.Set("sm2bm", sm2bm);

        static const USHORT kBmProbes[] = {
            0, BM_SAY, BM_WHISPER, BM_THINK, BM_ACTION,
            BM_ACTION | BM_SAY, BM_ACTION | BM_WHISPER, BM_ACTION | BM_THINK,
            BM_SOUND, BM_AWAY, BM_HERESINFO, BM_NOFORMAT, BM_EXCHAN,
            BM_SAY | BM_THINK
        };
        ojson::Value bm2sm = ojson::Value::Arr();
        for (int i = 0; i < (int)(sizeof(kBmProbes) / sizeof(kBmProbes[0])); i++) {
            ojson::Value e = ojson::Value::Obj();
            e.Set("in", ojson::Value::Int((long)kBmProbes[i]));
            e.Set("out", ojson::Value::Int((long)BM2SM(kBmProbes[i])));
            bm2sm.Push(e);
        }
        mm.Set("bm2sm", bm2sm);
        root.Set("modeMaps", mm);
    }

    // --- Tier-1 #7: formatting codec ------------------------------------
    {
        fprintf(stderr, "ORACLE: codecs - formatting\n"); fflush(stderr);
        ojson::Value fmt = ojson::Value::Obj();

        // nFillFormatting: every effect toggle in isolation, then the colour
        // paths. chFirstFormattedChar being a digit triggers the documented
        // ^k33 -> ^k0133 hack (format.cpp:502-508), so probe both sides of it.
        struct FillProbe { WORD cur; WORD next; char first; const char* note; };
        static const FillProbe kFill[] = {
            { 0,        0,          'a', "no change" },
            { 0,        wBold,      'a', "bold on" },
            { wBold,    0,          'a', "bold off" },
            { 0,        wItalic,    'a', "italic on" },
            { 0,        wUnderline, 'a', "underline on" },
            { 0,        wFixedPitch,'a', "fixed pitch on" },
            { 0,        wSymbol,    'a', "symbol on" },
            { 0,        (WORD)(wBold | wItalic | wUnderline), 'a', "three at once" },
            { 0x0033,   0,          '3', "colour off, digit follows - ^k33 hack" },
            { 0x0033,   0,          'x', "colour off, non-digit follows" },
            { 0,        0x0033,     '3', "colour on, digit follows" },
            { 0x0011,   0x0022,     'z', "colour change" }
        };
        ojson::Value fillArr = ojson::Value::Arr();
        for (int i = 0; i < (int)(sizeof(kFill) / sizeof(kFill[0])); i++) {
            char buf[128];
            memset(buf, 0, sizeof(buf));
            short n = nFillFormatting(buf, kFill[i].cur, kFill[i].next, kFill[i].first);
            ojson::Value e = ojson::Value::Obj();
            e.Set("note", ojson::Value::Str(kFill[i].note));
            e.Set("curFormat", ojson::Value::Int((long)kFill[i].cur));
            e.Set("nextFormat", ojson::Value::Int((long)kFill[i].next));
            e.Set("firstFormattedChar", ojson::Value::Int((long)(BYTE)kFill[i].first));
            e.Set("returned", ojson::Value::Int((long)n));
            e.Set("bytes", CodecStr(buf));
            ojson::Value raw = ojson::Value::Arr();
            for (short b = 0; b < n; b++) raw.Push(ojson::Value::Int((long)(BYTE)buf[b]));
            e.Set("byteValues", raw);
            fillArr.Push(e);
        }
        fmt.Set("nFillFormatting", fillArr);

        // SzControlLess: strips control codes out of the text and reports the
        // formatting runs it found. Input must be mutable.
        static const char* kLessProbes[] = {
            "plain text",
            "\x02" "bold then plain\x02 tail",
            "\x16" "italic\x16",
            "\x1F" "underline\x1F",
            "\x03" "04red text\x03",
            "mixed \x02" "bold \x16" "and italic\x16\x02 done",
            "\x11" "fixed\x11 \x12symbol\x12",
            "\x03" "33colour with two digits\x03"
        };
        ojson::Value lessArr = ojson::Value::Arr();
        for (int i = 0; i < (int)(sizeof(kLessProbes) / sizeof(kLessProbes[0])); i++) {
            fprintf(stderr, "ORACLE: codecs - szControlLess probe %d\n", i); fflush(stderr);
            char mutableIn[512];
            strncpy(mutableIn, kLessProbes[i], sizeof(mutableIn) - 1);
            mutableIn[sizeof(mutableIn) - 1] = 0;
            CDWordArray rgdw;
            char* out = SzControlLess(mutableIn, &rgdw);
            ojson::Value e = ojson::Value::Obj();
            e.Set("input", CodecStr(kLessProbes[i]));
            e.Set("output", CodecStr(out));
            e.Set("formatting", DumpFormattingArray(rgdw));
            lessArr.Push(e);
        }
        fmt.Set("szControlLess", lessArr);

        // SzControlFull: the inverse - re-inserts control codes from a
        // formatting array. ASSERTs on a NULL array, so always pass one.
        struct FullProbe { const char* text; int nRuns; DWORD runs[4]; };
        static const FullProbe kFull[] = {
            { "no formatting", 0, { 0, 0, 0, 0 } },
            { "bold from start", 1, { (DWORD)MAKELONG(wBold, 0), 0, 0, 0 } },
            { "half bold here", 2, { (DWORD)MAKELONG(wBold, 0), (DWORD)MAKELONG(0, 4), 0, 0 } },
            { "colour run", 1, { (DWORD)MAKELONG(0x0033, 0), 0, 0, 0 } },
            { "three runs total", 3, { (DWORD)MAKELONG(wBold, 0), (DWORD)MAKELONG(wItalic, 5), (DWORD)MAKELONG(0, 11), 0 } }
        };
        ojson::Value fullArr = ojson::Value::Arr();
        for (int i = 0; i < (int)(sizeof(kFull) / sizeof(kFull[0])); i++) {
            fprintf(stderr, "ORACLE: codecs - szControlFull probe %d\n", i); fflush(stderr);
            CDWordArray rgdw;
            for (int r = 0; r < kFull[i].nRuns; r++) rgdw.Add(kFull[i].runs[r]);
            char* out = SzControlFull(kFull[i].text, &rgdw);
            ojson::Value e = ojson::Value::Obj();
            e.Set("input", CodecStr(kFull[i].text));
            e.Set("formatting", DumpFormattingArray(rgdw));
            e.Set("output", CodecStr(out));
            fullArr.Push(e);
        }
        fmt.Set("szControlFull", fullArr);

        // The colour map the plan lists under #7. nFillFormatting encodes a
        // colour as ((format >> 4) & 0x0F) + 16 for the foreground and
        // (format & 0x0F) + 16 for the background, emitted as two ASCII
        // digits - so the meaningful code domain is 0..31. Round-tripped
        // through GetColorCode to show whether the mapping is injective.
        // (GetRBGColor's name transposes RGB; kept verbatim.)
        {
            ojson::Value colours = ojson::Value::Arr();
            for (int code = 0; code <= 31; code++) {
                COLORREF cr = GetRBGColor((BYTE)code);
                BYTE back = GetColorCode(cr);
                ojson::Value e = ojson::Value::Obj();
                e.Set("code", ojson::Value::Int((long)code));
                e.Set("colorref", ojson::Value::Int((long)cr));
                e.Set("r", ojson::Value::Int((long)GetRValue(cr)));
                e.Set("g", ojson::Value::Int((long)GetGValue(cr)));
                e.Set("b", ojson::Value::Int((long)GetBValue(cr)));
                e.Set("codeRoundTrip", ojson::Value::Int((long)back));
                e.Set("roundTrips", ojson::Value::Bool(back == (BYTE)code));
                colours.Push(e);
            }
            fmt.Set("colorMap", colours);
        }
        root.Set("formatting", fmt);
    }

    // --- Tier-1 #6: IRC line parse --------------------------------------
    {
        static const char* kIrcProbes[] = {
            ":nick!user@machine PRIVMSG #room :hello there",
            "PING :server.example.com",
            ":server 001 mynick :Welcome to the network",
            ":nick!user@machine JOIN #room",
            ":nick!user@machine JOIN :#room",
            "NOTICE AUTH :*** Looking up your hostname",
            // MAXARGS spill (ircsock.cpp:234 - `goto end` once nArgs hits 10,
            // dumping the remainder into lastString). The trailing part must NOT
            // begin with ':' or the whole tail collapses into lastString after
            // two args and the spill path never runs - which is what the first
            // version of this probe did.
            ":n!u@m PRIVMSG a b c d e f g h i j k l m n o p",
            ":n!u@m PRIVMSG #r :a b c d e f g h i j k l m n o p",
            ":n!u@m MODE #room +o someone",
            "",
            // NOT probed: a prefix with no following space, e.g.
            // ":only.a.prefix". ParseIt does `szBody = strchr(szMessage, ' ')`
            // then `ASSERT(szBody)` - "messages must have a body"
            // (ircsock.cpp:159) - and that assert is the only guard. In the
            // release build it compiles away and the next line computes
            // `szBody - szMessage` from a NULL, feeding garbage to strncpy.
            // That crashed this dump (0xC0000005) on its first run. The input
            // is outside the parser's stated contract, so it is left out
            // rather than pinned; the fragility is recorded in the LEDGER.
            ":n!u@m QUIT :Client exited \"with quotes\""
        };
        ojson::Value arr = ojson::Value::Arr();
        for (int i = 0; i < (int)(sizeof(kIrcProbes) / sizeof(kIrcProbes[0])); i++) {
            fprintf(stderr, "ORACLE: codecs - ircParse probe %d\n", i); fflush(stderr);
            IRCPARSE parse;
            memset(&parse, 0, sizeof(parse));
            ParseIt(kIrcProbes[i], &parse);
            ojson::Value e = ojson::Value::Obj();
            e.Set("line", CodecStr(kIrcProbes[i]));
            e.Set("bHasPrefix", ojson::Value::Bool(parse.bHasPrefix ? true : false));
            e.Set("nick", CodecStr(parse.nick));
            e.Set("user", CodecStr(parse.user));
            e.Set("machine", CodecStr(parse.machine));
            e.Set("uCode", ojson::Value::Int((long)parse.uCode));
            e.Set("nArgs", ojson::Value::Int((long)parse.nArgs));
            ojson::Value args = ojson::Value::Arr(), offs = ojson::Value::Arr();
            for (int a = 0; a < parse.nArgs && a < MAXARGS; a++) {
                args.Push(CodecStr(parse.args[a]));
                offs.Push(ojson::Value::Int((long)parse.nOffsets[a]));
            }
            e.Set("args", args);
            e.Set("nOffsets", offs);
            // lastString is where the trailing ":..." payload lands - the
            // message text itself for PRIVMSG, and everything past MAXARGS when
            // a line spills. Dumping args without it would pin the envelope and
            // drop the letter.
            e.Set("lastString", CodecStr(parse.lastString));
            e.Set("hasLastString", ojson::Value::Bool(parse.lastString ? true : false));
            arr.Push(e);
            FreeParse(&parse);
        }
        root.Set("ircParse", arr);
    }

    // --- Tier-1 #8: URL detection (live path) ---------------------------
    {
        static const char* kUrlProbes[] = {
            "no url here at all",
            "visit http://www.example.com now",
            "https://secure.example.com/path?q=1&r=2",
            "www.example.com without a scheme",
            "mic://chat.example.com/room is the Comic Chat scheme",
            "irc://irc.example.com/room too",
            "trailing punctuation http://example.com.",
            "in parens (http://example.com) here",
            "two http://a.example.com and http://b.example.com urls",
            "mailto:someone@example.com address",
            "ftp://files.example.com/pub/file.txt",
            "percent escapes http://example.com/%41%42 here"
        };
        ojson::Value arr = ojson::Value::Arr();
        for (int i = 0; i < (int)(sizeof(kUrlProbes) / sizeof(kUrlProbes[0])); i++) {
            fprintf(stderr, "ORACLE: codecs - url probe %d\n", i); fflush(stderr);
            int bounds[MAX_URL_INTEXT * 2];
            memset(bounds, 0, sizeof(bounds));
            int nUrls = MAX_URL_INTEXT;
            // HrIdentifyUrls takes LPCTSTR but writes through it: it stamps a
            // terminator over the scheme's colon to test the prefix and then
            // restores it (artifacts-modern/core/urlutil.cpp:311-313). Passing a
            // string literal therefore faults on read-only memory - which is
            // exactly how this dump crashed on its first URL probe, while the
            // no-colon probe before it survived. The buffer must be writable.
            char mutableUrl[512];
            strncpy(mutableUrl, kUrlProbes[i], sizeof(mutableUrl) - 1);
            mutableUrl[sizeof(mutableUrl) - 1] = 0;
            HRESULT hr = g_urlRec.HrIdentifyUrls(mutableUrl, bounds, &nUrls);
            ojson::Value e = ojson::Value::Obj();
            e.Set("text", CodecStr(kUrlProbes[i]));
            e.Set("hr", ojson::Value::Int((long)hr));
            e.Set("nUrlNum", ojson::Value::Int((long)nUrls));
            ojson::Value bb = ojson::Value::Arr();
            ojson::Value found = ojson::Value::Arr();
            for (int u = 0; u < nUrls && u < MAX_URL_INTEXT; u++) {
                ojson::Value pair = ojson::Value::Obj();
                pair.Set("start", ojson::Value::Int((long)bounds[u * 2]));
                pair.Set("end", ojson::Value::Int((long)bounds[u * 2 + 1]));
                bb.Push(pair);
                // The substring the bounds select, so a divergence is readable
                // without cross-referencing offsets by hand.
                int s = bounds[u * 2], e2 = bounds[u * 2 + 1];
                if (s >= 0 && e2 >= s && e2 <= (int)strlen(mutableUrl)) {
                    std::string sub(mutableUrl + s, (size_t)(e2 - s));
                    found.Push(ojson::Value::Str(sub));
                }
            }
            e.Set("bounds", bb);
            e.Set("substrings", found);
            arr.Push(e);
        }
        root.Set("urls", arr);
    }

    // --- Tier-1 #12: CDosKey ring buffer --------------------------------
    // The interesting behaviour is wraparound: append past the cap and walk
    // backwards, which exercises the modulo arithmetic over m_iStartIndex /
    // m_iEndIndex / m_iCurIndex.
    {
        fprintf(stderr, "ORACLE: codecs - doskey\n"); fflush(stderr);
        ojson::Value dk = ojson::Value::Obj();
        const UINT kMax = 4;
        CDosKey key;
        key.SetMaxSize(kMax);
        dk.Set("maxSize", ojson::Value::Int((long)kMax));

        ojson::Value appended = ojson::Value::Arr();
        static const char* kEntries[] = { "one", "two", "three", "four", "five", "six" };
        for (int i = 0; i < (int)(sizeof(kEntries) / sizeof(kEntries[0])); i++) {
            BOOL ok = key.bAppendEntry(CString(kEntries[i]), NULL);
            ojson::Value e = ojson::Value::Obj();
            e.Set("entry", ojson::Value::Str(kEntries[i]));
            e.Set("accepted", ojson::Value::Bool(ok ? true : false));
            appended.Push(e);
        }
        dk.Set("appended", appended);

        // Walk backwards past the end, then forwards again. Six appends into a
        // four-slot ring means the first two should be gone.
        key.SeekToEnd();
        ojson::Value prev = ojson::Value::Arr();
        for (int i = 0; i < 6; i++) {
            CDWordArray* fmt = NULL;
            CString s = key.StrGetPrevEntry(&fmt);
            prev.Push(CodecStr((const char*)s));
        }
        dk.Set("walkPrev", prev);

        ojson::Value next = ojson::Value::Arr();
        for (int i = 0; i < 6; i++) {
            CDWordArray* fmt = NULL;
            CString s = key.StrGetNextEntry(&fmt);
            next.Push(CodecStr((const char*)s));
        }
        dk.Set("walkNext", next);

        // And an empty ring, since ResetContent is its own path.
        key.ResetContent();
        CDWordArray* fmt = NULL;
        dk.Set("afterResetPrev", CodecStr((const char*)key.StrGetPrevEntry(&fmt)));
        root.Set("doskey", dk);
    }

    return root;
}

// ---------------------------------------------------------------------------
// Tier-1 #10: the .ccc transcript codec (histent.cpp).
//
// The plan asks for byte-exact WriteSelf goldens plus parse-then-serialize
// identity across all nine entry keywords. Rather than hand-writing .ccc lines
// (and risking pinning my transcription instead of the format), each entry is
// built with its live constructor, serialised, re-parsed through the
// CString constructor, and serialised again. Identity between the two
// serialisations is the round-trip proof, and the first serialisation is the
// byte golden.
//
// A CChatDoc is required: SayEntry's parse ctor calls LookupPui(nick, doc) and
// fabricates a CUserInfo through CIUserJoin when the nick is unknown ("got a
// say without a join -- fake it").
// ---------------------------------------------------------------------------

// Serialise one entry through a CArchive over a CMemFile. The archive must be
// closed before the file is read back or the tail sits in the archive buffer.
static std::string WriteEntryBytes(HistoryEntry* entry) {
    CMemFile mf;
    {
        CArchive ar(&mf, CArchive::store);
        entry->WriteSelf(ar);
        ar.Close();
    }
    UINT len = (UINT)mf.GetLength();
    mf.SeekToBegin();
    std::string out;
    if (len) {
        out.resize(len);
        mf.Read(&out[0], len);
    }
    return out;
}

static ojson::Value DumpBytes(const std::string& s) {
    ojson::Value v = ojson::Value::Obj();
    v.Set("text", ojson::Value::Str(s));
    v.Set("length", ojson::Value::Int((long)s.size()));
    // Hex too: the format is tab and CRLF delimited, and those are exactly the
    // bytes a diff of escaped text is easiest to misread.
    std::string hex;
    static const char* kHexDigits = "0123456789abcdef";
    for (size_t i = 0; i < s.size(); i++) {
        unsigned char c = (unsigned char)s[i];
        if (i) hex += ' ';
        hex += kHexDigits[(c >> 4) & 0x0F];
        hex += kHexDigits[c & 0x0F];
    }
    v.Set("hex", ojson::Value::Str(hex));
    return v;
}

// Serialise, re-parse via the supplied parser, serialise again, and report
// whether the two byte strings agree.
typedef HistoryEntry* (*CccParser)(CString& line, CChatDoc* doc);

static ojson::Value RoundTripEntry(const char* keyword, HistoryEntry* live,
                                   CccParser parse, CChatDoc* doc) {
    ojson::Value e = ojson::Value::Obj();
    e.Set("keyword", ojson::Value::Str(keyword));

    fprintf(stderr, "ORACLE: ccc - %s serialise\n", keyword); fflush(stderr);
    std::string first = WriteEntryBytes(live);
    e.Set("written", DumpBytes(first));

    if (!parse) {
        e.Set("reparsed", ojson::Value::Str("(no CString parser exercised)"));
        return e;
    }

    fprintf(stderr, "ORACLE: ccc - %s reparse\n", keyword); fflush(stderr);
    // Strip the record terminator before re-parsing. A .ccc reader consumes
    // whole lines and hands over the content without the CRLF; feeding it back
    // in makes the terminator part of the final field, so every entry came back
    // with a doubled CRLF and the say variants had theirs re-quoted as a
    // literal \r\n by QuoteReturns. That was the harness misreading the format,
    // not the codec failing to round-trip.
    std::string body = first;
    while (!body.empty() && (body[body.size() - 1] == '\n' || body[body.size() - 1] == '\r')) {
        body.erase(body.size() - 1);
    }
    e.Set("reparsedFrom", ojson::Value::Str(body));
    CString line(body.c_str());
    HistoryEntry* again = parse(line, doc);
    if (!again) {
        e.Set("reparseFailed", ojson::Value::Bool(true));
        return e;
    }
    std::string second = WriteEntryBytes(again);
    e.Set("rewritten", DumpBytes(second));
    e.Set("roundTrips", ojson::Value::Bool(first == second));
    delete again;
    return e;
}

// One thunk per keyword, because the parse constructors do not share a
// signature (SayEntry wants the doc, JoinEntry a highlight type, the rest just
// the line).
static HistoryEntry* ParseSay(CString& l, CChatDoc* d) { return new SayEntry(l, d, (char)-1); }
static HistoryEntry* ParseJoin(CString& l, CChatDoc*) { return new JoinEntry(l, (char)-1); }
static HistoryEntry* ParsePart(CString& l, CChatDoc*) { return new PartEntry(l); }
static HistoryEntry* ParseChangeAvatar(CString& l, CChatDoc*) { return new ChangeAvatarEntry(l); }
static HistoryEntry* ParseGetInfo(CString& l, CChatDoc*) { return new GetInfoEntry(l); }
static HistoryEntry* ParseComicCharacter(CString& l, CChatDoc*) { return new ComicCharacterEntry(l); }
static HistoryEntry* ParseStartHistory(CString& l, CChatDoc*) { return new StartHistoryEntry(l); }
static HistoryEntry* ParseChangeBackDrop(CString& l, CChatDoc*) { return new ChangeBackDropEntry(l); }
static HistoryEntry* ParseNick(CString& l, CChatDoc*) { return new NickEntry(l); }

static ojson::Value CaptureCcc(CChatDoc* doc) {
    ojson::Value root = ojson::Value::Obj();
    ojson::Value entries = ojson::Value::Arr();

    // A user info to hang the speaker-bearing entries off.
    CUserInfo* pui = new CUserInfo(CString("oraclenick"));

    // Register it in the doc's nick map so the parse constructors resolve the
    // speaker through LookupPui. Without this they fall into
    // CIUserJoin (histent.cpp:236, "got a say without a join -- fake it"),
    // which is not survivable on a bare doc: it dereferences
    // doc->m_proto->m_dwModes (protsupp.cpp:577), calls AssignArbitraryAvatar,
    // and appends to the members list - protocol and UI state a codec dump has
    // no business standing up. That crashed the first run right after "say
    // serialise". Registering the nick keeps the dump on the codec path.
    doc->m_mapNickToPtr.SetAt("oraclenick", (void*)pui);

    // say, plain
    {
        SayEntry* e = new SayEntry(pui, "hello transcript", NULL, (char)-1);
        entries.Push(RoundTripEntry("say", e, ParseSay, doc));
        delete e;
    }
    // say, with formatting - WriteSelf runs the text back through
    // SzControlFull, so this is where #7 and #10 meet.
    {
        CDWordArray* fmt = new CDWordArray;
        fmt->Add((DWORD)MAKELONG(wBold, 0));
        fmt->Add((DWORD)MAKELONG(0, 5));
        SayEntry* e = new SayEntry(pui, "bold start then plain", fmt, (char)-1);
        entries.Push(RoundTripEntry("say+formatting", e, ParseSay, doc));
        delete e;
    }
    // say, with an embedded newline: WriteSelf calls QuoteReturns, since a
    // transcript line cannot contain a raw CRLF.
    {
        SayEntry* e = new SayEntry(pui, "first line\r\nsecond line", NULL, (char)-1);
        entries.Push(RoundTripEntry("say+returns", e, ParseSay, doc));
        delete e;
    }
    {
        JoinEntry* e = new JoinEntry(pui, TRUE, (char)-1);
        entries.Push(RoundTripEntry("join", e, ParseJoin, doc));
        delete e;
    }
    {
        PartEntry* e = new PartEntry("oraclenick", (char)-1);
        entries.Push(RoundTripEntry("part", e, ParsePart, doc));
        delete e;
    }
    {
        ChangeAvatarEntry* e = new ChangeAvatarEntry(pui, "bolo", "http://example.com/bolo.avb");
        entries.Push(RoundTripEntry("changeavatar", e, ParseChangeAvatar, doc));
        delete e;
    }
    {
        GetInfoEntry* e = new GetInfoEntry(pui, (char*)"some info text");
        entries.Push(RoundTripEntry("getinfo", e, ParseGetInfo, doc));
        delete e;
    }
    {
        ComicCharacterEntry* e = new ComicCharacterEntry(pui);
        entries.Push(RoundTripEntry("comiccharacter", e, ParseComicCharacter, doc));
        delete e;
    }
    // StartHistoryEntry carries the PRNG seed. Plan section 4.3 records that
    // WriteSelf does not persist m_randStart, so a .ccc cannot reproduce a
    // comic on its own - this golden is the evidence for that claim.
    {
        StartHistoryEntry* e = new StartHistoryEntry("Oracle Comic", "bolo", 12345);
        entries.Push(RoundTripEntry("starthistory", e, ParseStartHistory, doc));
        delete e;
    }
    {
        ChangeBackDropEntry* e = new ChangeBackDropEntry("cityscape", "http://example.com/city.bgb");
        entries.Push(RoundTripEntry("changebackdrop", e, ParseChangeBackDrop, doc));
        delete e;
    }
    {
        NickEntry* e = new NickEntry("oldnick", "newnick");
        entries.Push(RoundTripEntry("nick", e, ParseNick, doc));
        delete e;
    }

    root.Set("entries", entries);
    return root;
}

// ---------------------------------------------------------------------------
// Dump a SRECT as a JSON object
// ---------------------------------------------------------------------------
static ojson::Value DumpSRECT(const SRECT& r) {
    ojson::Value v = ojson::Value::Obj();
    v.Set("left", ojson::Value::Int(r.Left));
    v.Set("top", ojson::Value::Int(r.Top));
    v.Set("right", ojson::Value::Int(r.Right));
    v.Set("bottom", ojson::Value::Int(r.Bottom));
    return v;
}

// ---------------------------------------------------------------------------
// Dump a RECT as a JSON object
// ---------------------------------------------------------------------------
static ojson::Value DumpRECT(const RECT& r) {
    ojson::Value v = ojson::Value::Obj();
    v.Set("left", ojson::Value::Int(r.left));
    v.Set("top", ojson::Value::Int(r.top));
    v.Set("right", ojson::Value::Int(r.right));
    v.Set("bottom", ojson::Value::Int(r.bottom));
    return v;
}

// ---------------------------------------------------------------------------
// Dump an {emotion, intensity} pair. FACEREC/BODYREC/RBODYREC all store these
// as floats; widened to double so ojson emits them at %.17g, matching how the
// textpose and avatario dumps express their emotion floats.
// ---------------------------------------------------------------------------
static ojson::Value DumpEmotionPair(float emotion, float intensity) {
    ojson::Value v = ojson::Value::Obj();
    v.Set("emotion", ojson::Value::Dbl((double)emotion));
    v.Set("intensity", ojson::Value::Dbl((double)intensity));
    return v;
}

// ---------------------------------------------------------------------------
// Dump a POINT as a JSON object (spline cps, traj segment endpoints)
// ---------------------------------------------------------------------------
static ojson::Value DumpPOINT(const POINT& p) {
    ojson::Value v = ojson::Value::Obj();
    v.Set("x", ojson::Value::Int(p.x));
    v.Set("y", ojson::Value::Int(p.y));
    return v;
}

// ---------------------------------------------------------------------------
// Dump CFormatInfo (Tier-3 #4: line-break output)
// ---------------------------------------------------------------------------
static ojson::Value DumpFormatInfo(const CFormatInfo& fi) {
    ojson::Value v = ojson::Value::Obj();
    v.Set("nLines", ojson::Value::Int(fi.m_nLines));
    v.Set("maxWidth", ojson::Value::Int(fi.m_iMaxWidth));

    ojson::Value lengths = ojson::Value::Arr();
    ojson::Value widths = ojson::Value::Arr();
    ojson::Value leftX = ojson::Value::Arr();
    ojson::Value starts = ojson::Value::Arr();
    for (int i = 0; i < fi.m_nLines; i++) {
        lengths.Push(ojson::Value::Int(fi.m_rgiLengths[i]));
        widths.Push(ojson::Value::Int(fi.m_rgiWidths[i]));
        leftX.Push(ojson::Value::Int(fi.m_rgiLeftX[i]));
        // m_rgszStarts are char pointers into the label text
        starts.Push(ojson::Value::Int((long)(fi.m_rgszStarts[i] - fi.m_rgszStarts[0])));
    }
    v.Set("rgiLengths", lengths);
    v.Set("rgiWidths", widths);
    v.Set("rgiLeftX", leftX);
    v.Set("rgiStartOffsets", starts);
    v.Set("bbox", DumpSRECT(fi.m_bbox));
    return v;
}

// ---------------------------------------------------------------------------
// Dump a CBalloon (Tier-3 #5/#6: balloon bbox/routeRgn/tail + spline cps)
// ---------------------------------------------------------------------------
static ojson::Value DumpBalloon(CBalloon* balloon) {
    ojson::Value v = ojson::Value::Obj();

    // Balloon bbox
    RECT bbox;
    balloon->GetBBox(&bbox);
    v.Set("bbox", DumpRECT(bbox));

    // trueBox and routeRgn (SRECT, relative to balloon origin)
    v.Set("trueBox", DumpSRECT(balloon->m_trueBox));
    v.Set("routeRgn", DumpSRECT(balloon->m_routeRgn));

    // CFormatInfo (line breaks)
    if (balloon->m_fInfo) {
        v.Set("formatInfo", DumpFormatInfo(*balloon->m_fInfo));
    }

    // Spline control points (Tier-3 #6)
    if (balloon->m_spline) {
        CSpline* sp = balloon->m_spline;
        ojson::Value spline = ojson::Value::Obj();
        spline.Set("nCps", ojson::Value::Int(sp->nCps));
        spline.Set("closed", ojson::Value::Bool(sp->closed ? true : false));

        ojson::Value cps = ojson::Value::Arr();
        for (int i = 0; i < sp->nCps; i++) {
            ojson::Value cp = ojson::Value::Obj();
            cp.Set("x", ojson::Value::Int(sp->cps[i].x));
            cp.Set("y", ojson::Value::Int(sp->cps[i].y));
            cps.Push(cp);
        }
        spline.Set("cps", cps);

        // Bezier points (computed by ComputeBezpts).
        // The bezpts array is allocated with exactly BezierCount() entries
        // (spline.cpp:175) and ComputeBezpts writes bezpts[0] then 3 per
        // cubic segment up to BezierCount() total. BezierCount = 3*KnotCount-8.
        // Reading past BezierCount() yields uninitialized memory and
        // non-deterministic dumps, so bound the loop strictly by BezierCount().
        if (sp->bezpts) {
            int knotCount = sp->KnotCount();
            int bezCount = sp->BezierCount();
            ojson::Value bez = ojson::Value::Arr();
            int nBezPts = bezCount;  // exact allocation, no overread
            for (int i = 0; i < nBezPts; i++) {
                ojson::Value bp = ojson::Value::Obj();
                bp.Set("x", ojson::Value::Int(sp->bezpts[i].x));
                bp.Set("y", ojson::Value::Int(sp->bezpts[i].y));
                bez.Push(bp);
            }
            spline.Set("bezpts", bez);
            spline.Set("bezierCount", ojson::Value::Int(bezCount));
            spline.Set("knotCount", ojson::Value::Int(knotCount));
        }

        v.Set("spline", spline);
    }

    // Tail/arrow geometry (Tier-3 #5). m_traj is NULL after layout: the app
    // only builds it at draw time (balloon.cpp:1788 calls SetBalloonTraj from
    // Draw), so a headless dump saw nothing and the tail went unpinned. Build
    // it here explicitly. SetBalloonTraj clones m_spline and runs AddArrow
    // over the clone, so the balloon's own spline - already dumped above - is
    // not disturbed; m_traj is draw-only state that Draw would rebuild anyway.
    //
    // Segments are heterogeneous: SetBalloonTraj adds the cloned CSpline, then
    // AddArrow appends the two CArc tail strokes (balloon.cpp:1527-1529);
    // CBWoodringBox instead adds four CLines. All derive from CSeg, which is
    // polymorphic, so dynamic_cast is the discriminator.
    // SetBalloonTraj is declared on CBWoodringNormal, not CBalloon, and in a
    // release build the ASSERTs inside it compile away - so m_spline/m_fInfo
    // must be checked here or a partially built balloon would deref NULL.
    // CBWoodringNormal::AddArrow also reads m_speaker->m_arrowX; the Box
    // override doesn't, so only the non-Box path requires a speaker. When a
    // balloon can't be built, say so rather than silently omitting the field.
    CBWoodringNormal* bn = dynamic_cast<CBWoodringNormal*>(balloon);
    bool isBox = dynamic_cast<CBWoodringBox*>(balloon) != NULL;
    // A box balloon has no m_spline at all: CBWoodringBox::SetBalloonTraj draws
    // four CLines straight off m_fInfo->m_bbox and never touches a spline or a
    // speaker. Requiring m_spline for every balloon skipped all 8 box balloons
    // in case 015 (they reported trajSkipped "no spline or formatInfo"), which
    // is why the traj census still showed zero line segments after BM_ACTION
    // was finally being sent. m_fInfo is the only universal requirement.
    if (!bn) {
        v.Set("trajSkipped", ojson::Value::Str("not a CBWoodringNormal"));
    } else if (!balloon->m_fInfo) {
        v.Set("trajSkipped", ojson::Value::Str("no formatInfo"));
    } else if (!isBox && !balloon->m_spline) {
        v.Set("trajSkipped", ojson::Value::Str("no spline to clone for the outline"));
    } else if (!isBox && !balloon->m_speaker) {
        v.Set("trajSkipped", ojson::Value::Str("no speaker for arrow"));
    } else {
        bn->SetBalloonTraj();
    }

    if (balloon->m_traj) {
        CTraj* traj = balloon->m_traj;
        ojson::Value tj = ojson::Value::Obj();
        tj.Set("closed", ojson::Value::Bool(traj->m_closed ? true : false));

        ojson::Value segs = ojson::Value::Arr();
        POSITION spos = traj->m_segs.GetHeadPosition();
        while (spos) {
            CSeg* seg = (CSeg*)traj->m_segs.GetNext(spos);
            ojson::Value s = ojson::Value::Obj();
            if (CArc* arc = dynamic_cast<CArc*>(seg)) {
                s.Set("type", ojson::Value::Str("arc"));
                s.Set("lo", DumpPOINT(arc->m_lo));
                s.Set("hi", DumpPOINT(arc->m_hi));
                s.Set("altitude", ojson::Value::Int(arc->m_altitude));
            } else if (CLine* line = dynamic_cast<CLine*>(seg)) {
                s.Set("type", ojson::Value::Str("line"));
                s.Set("lo", DumpPOINT(line->m_lo));
                s.Set("hi", DumpPOINT(line->m_hi));
            } else if (CSpline* sp = dynamic_cast<CSpline*>(seg)) {
                // The arrow-broken outline: AddArrow calls BreakSpline on this
                // clone, so its cps differ from the balloon's own spline. That
                // difference is the whole point of pinning it.
                s.Set("type", ojson::Value::Str("spline"));
                s.Set("nCps", ojson::Value::Int(sp->nCps));
                ojson::Value cps = ojson::Value::Arr();
                for (int i = 0; i < sp->nCps; i++) {
                    cps.Push(DumpPOINT(sp->cps[i]));
                }
                s.Set("cps", cps);
            } else {
                s.Set("type", ojson::Value::Str("unknown"));
            }
            segs.Push(s);
        }
        tj.Set("segs", segs);
        v.Set("traj", tj);
    }

    // Speaker
    if (balloon->m_speaker) {
        v.Set("speakerAvatarID", ojson::Value::Int(balloon->m_speaker->m_avatarID));
        v.Set("speakerFlip", ojson::Value::Int(balloon->m_speaker->m_flip));
    }

    // Balloon type
    v.Set("type", ojson::Value::Int(balloon->GetType()));

    return v;
}

// ---------------------------------------------------------------------------
// Dump a CPanel (Tier-3 #1-3: membership, avatar order/flip, zoom, body rects)
// ---------------------------------------------------------------------------
static ojson::Value DumpPanel(CPanel* panel) {
    ojson::Value v = ojson::Value::Obj();

    v.Set("seed", ojson::Value::Int((long)panel->m_seed));
    v.Set("hasBorder", ojson::Value::Bool(panel->m_hasBorder ? true : false));

    // Tier-3 #3: the zoom decision. zoomFactor is a local in LayoutAvatars and
    // Establishing() reads view state, so panel.cpp records both at the
    // decision site under ORACLE_HARNESS. backDropMode matters because
    // AdjustArtToCoord forces the factor to 1.0 when the backdrop is
    // BF_NOZOOM, so the factor alone doesn't explain the art placement.
    v.Set("zoomFactor", ojson::Value::Dbl(panel->m_oracleZoomFactor));
    v.Set("reduction", ojson::Value::Dbl(panel->m_oracleReduction));
    v.Set("establishing", ojson::Value::Bool(panel->m_oracleEstablishing ? true : false));
    v.Set("backDropMode", ojson::Value::Int(panel->m_backDrop.m_mode));
    v.Set("backDropID", ojson::Value::Int(panel->m_backDrop.m_backID));

    // Balloons (m_elements)
    ojson::Value balloons = ojson::Value::Arr();
    POSITION pos = panel->m_elements.GetHeadPosition();
    while (pos) {
        CPanelElement* elem = (CPanelElement*)panel->m_elements.GetNext(pos);
        if (elem->GetType() & PE_BALLOON) {
            balloons.Push(DumpBalloon((CBalloon*)elem));
        }
    }
    v.Set("balloons", balloons);

    // Bodies (m_bodies) - avatar order, flip, bbox
    ojson::Value bodies = ojson::Value::Arr();
    POSITION bpos = panel->m_bodies.GetHeadPosition();
    while (bpos) {
        CBody* body = (CBody*)panel->m_bodies.GetNext(bpos);
        ojson::Value b = ojson::Value::Obj();
        b.Set("avatarID", ojson::Value::Int(body->m_avatarID));
        b.Set("flip", ojson::Value::Int(body->m_flip));
        b.Set("requested", ojson::Value::Int(body->m_requested));
        b.Set("bbox", DumpSRECT(body->m_bbox));
        b.Set("arrowX", ojson::Value::Int(body->m_arrowX));
        b.Set("class", ojson::Value::Int(body->GetClass()));

        // The pose this panel actually drew (Tier-3 #7 for the panel path).
        //
        // This is NOT the same as the pose in avatarStates. That one comes from
        // CAvatarX after the message, by which point ResetAvatar has called
        // SetNeutral - and SetFaceNeutral/SetTorsoNeutral scan round-robin from
        // m_lastFace/m_lastTorso for the *next* neutral pose, so the avatar's
        // indices legitimately keep changing while its emotion stays
        // EM_NEUTRAL (0.0). That is why every avatarStates emotion reads {0,0}:
        // faithful, but the post-message neutral, not the pose the reader sees.
        // The emotional pose selected by GetBodyFromEmotion lives here, on the
        // panel's own CBody, and until now nothing dumped it.
        CAvatarX* bodyAv = GetAvatar(body->m_avatarID);
        if (body->GetClass() == BC_BODYDOUBLE) {
            CBodyDouble* bd = (CBodyDouble*)body;
            CAvatarComplex* ac = dynamic_cast<CAvatarComplex*>(bodyAv);
            if (bd->m_faceRec && ac && ac->fRec) {
                b.Set("faceIndex", ojson::Value::Int((long)(bd->m_faceRec - ac->fRec)));
                b.Set("faceEmotion", DumpEmotionPair(bd->m_faceRec->emotion, bd->m_faceRec->intensity));
                b.Set("facePoseID", ojson::Value::Int(bd->m_faceRec->poseID));
            }
            if (bd->m_torsoRec && ac && ac->bRec) {
                b.Set("torsoIndex", ojson::Value::Int((long)(bd->m_torsoRec - ac->bRec)));
                b.Set("torsoEmotion", DumpEmotionPair(bd->m_torsoRec->emotion, bd->m_torsoRec->intensity));
                b.Set("torsoPoseID", ojson::Value::Int(bd->m_torsoRec->poseID));
            }
        } else if (body->GetClass() == BC_BODYSINGLE) {
            // Simple avatars carry one record; CAvatarSimple::GetEmotions
            // reports it as the face and forces the torso to zero.
            CBodySingle* bs = (CBodySingle*)body;
            CAvatarSimple* as = dynamic_cast<CAvatarSimple*>(bodyAv);
            if (bs->m_bodyRec && as && as->bRec) {
                b.Set("bodyIndex", ojson::Value::Int((long)(bs->m_bodyRec - as->bRec)));
                b.Set("bodyEmotion", DumpEmotionPair(bs->m_bodyRec->emotion, bs->m_bodyRec->intensity));
                b.Set("bodyPoseID", ojson::Value::Int(bs->m_bodyRec->poseID));
            }
        }
        bodies.Push(b);
    }
    v.Set("bodies", bodies);

    return v;
}

// ---------------------------------------------------------------------------
// Dump a CPage (the page with its panels)
// ---------------------------------------------------------------------------
static ojson::Value DumpPage(CPage* page) {
    ojson::Value v = ojson::Value::Obj();
    v.Set("newPanel", ojson::Value::Bool(page->m_newPanel ? true : false));

    RECT bbox;
    page->GetBBox(&bbox);
    v.Set("bbox", DumpRECT(bbox));

    ojson::Value panels = ojson::Value::Arr();
    POSITION pos = page->m_panels.GetHeadPosition();
    while (pos) {
        CPanel* panel = (CPanel*)page->m_panels.GetNext(pos);
        panels.Push(DumpPanel(panel));
    }
    v.Set("panels", panels);

    return v;
}

// ---------------------------------------------------------------------------
// Dump seed ledger (Phase 0: every seed recorded)
// ---------------------------------------------------------------------------
static ojson::Value DumpSeedLedger() {
    ojson::Value v = ojson::Value::Arr();
    int n = OracleSeedRecordCount();
    for (int i = 0; i < n; i++) {
        const OracleSeedRecord* r = OracleSeedRecordAt(i);
        ojson::Value entry = ojson::Value::Obj();
        entry.Set("site", ojson::Value::Str(r->site));
        entry.Set("value", ojson::Value::Int(r->value));
        v.Push(entry);
    }
    return v;
}

// ---------------------------------------------------------------------------
// Dump avatar state (Tier-3 #7: hidden state)
// ---------------------------------------------------------------------------
static ojson::Value DumpAvatarState(USHORT avatarID) {
    ojson::Value v = ojson::Value::Obj();
    CAvatarX* av = GetAvatar(avatarID);
    if (!av) {
        v.Set("exists", ojson::Value::Bool(false));
        return v;
    }
    v.Set("exists", ojson::Value::Bool(true));
    v.Set("name", ojson::Value::Str(av->m_name ? av->m_name : ""));
    v.Set("lastDir", ojson::Value::Int(av->m_lastDir));
    v.Set("lastRight", ojson::Value::Int(av->m_lastRight));
    v.Set("lastLeft", ojson::Value::Int(av->m_lastLeft));
    v.Set("nSends", ojson::Value::Int(av->m_nSends));

    if (av->m_body) {
        ojson::Value body = ojson::Value::Obj();
        body.Set("class", ojson::Value::Int(av->m_body->GetClass()));
        body.Set("flip", ojson::Value::Int(av->m_body->m_flip));
        // NOTE: the avatar's neutral-body m_bbox is only populated by the body
        // cam's DrawBody path (RefreshBody), which the headless harness does
        // not run. Dumping it here would capture uninitialized SRECT.Top/Bottom
        // (CPanelElement ctor only sets Left/Right = -1) and break determinism.
        // The per-panel body bboxes (set by CUnitPanel::LayoutAvatars via
        // SetBBox) are dumped separately in DumpPanel and are the Tier-3 #3
        // target, so we omit the neutral bbox here.

        // Get emotion state
        CEmotion face, torso;
        av->GetEmotions(face, torso);
        ojson::Value fE = ojson::Value::Obj();
        fE.Set("emotion", ojson::Value::Dbl(face.m_emotion));
        fE.Set("intensity", ojson::Value::Dbl(face.m_intensity));
        body.Set("faceEmotion", fE);
        ojson::Value tE = ojson::Value::Obj();
        tE.Set("emotion", ojson::Value::Dbl(torso.m_emotion));
        tE.Set("intensity", ojson::Value::Dbl(torso.m_intensity));
        body.Set("torsoEmotion", tE);

        // Get indices
        CHAR chFace, chTorso;
        BYTE bbReq;
        av->GetIndices(chFace, chTorso, bbReq);
        body.Set("faceIndex", ojson::Value::Int(chFace));
        body.Set("torsoIndex", ojson::Value::Int(chTorso));
        body.Set("bbRequested", ojson::Value::Int(bbReq));

        v.Set("body", body);
    }
    return v;
}

// The Tier-2 .avb/.bgb dump lives in avbdump.cpp, not here. It is shared with the
// NATIVE macOS build (native/avbmain.cpp), which is the point: "the native port
// reproduces the frozen goldens" is only a strong claim if both binaries run the
// SAME dump code on two platforms rather than two implementations that agree.
#include "avbdump.h"


// ---------------------------------------------------------------------------
// Initialize the harness environment (fonts, emotion rules, avatars, DC)
// ---------------------------------------------------------------------------
static void InitHarness(const char* treeDir) {
    fprintf(stderr, "ORACLE: InitHarness start\n");
    
    // MFC requires AfxWinInit for basic functionality
    AfxWinInit(GetModuleHandle(NULL), NULL, ::GetCommandLine(), SW_HIDE);
    
    // OLE/control container init (normally in CChatApp::InitInstance)
    AfxOleInit();
    AfxEnableControlContainer();
    
    fprintf(stderr, "ORACLE: AfxWinInit + OLE init done\n");

    // Set up the global DC: desktop CClientDC with MM_TWIPS
    // (same as pageview.cpp:994-998)
    if (!cui.m_pvClientDC) {
        CClientDC* dc = new CClientDC(CWnd::FromHandle(::GetDesktopWindow()));
        dc->SetMapMode(MM_TWIPS);
        cui.m_pvClientDC = dc;
    }
    fprintf(stderr, "ORACLE: DC created\n");

    // Pin panel dimensions BEFORE SetFonts (UpdateTitleFonts depends on m_unitWidth)
    CUnitPanelPage::SetUnitPanelsPerRow(2);
    CUnitPanelPage::SetUnitPanelWidth(4860);  // pin world width
    CUnitPanelPage::SetUnitPanelHeight(4860);

    // Initialize fonts directly (replicates chat.cpp:495 + InitializeComicsFonts)
    // Pin: Comic Sans MS, 12pt -> twips
    int fontHeight = PointsToTwips(12);
    memset(&theApp.m_comicsFont, 0, sizeof(LOGFONT));
    theApp.m_comicsFont.lfHeight = fontHeight;
    theApp.m_comicsFont.lfWidth = 0;
    theApp.m_comicsFont.lfWeight = FW_NORMAL;
    theApp.m_comicsFont.lfItalic = FALSE;
    theApp.m_comicsFont.lfUnderline = FALSE;
    theApp.m_comicsFont.lfStrikeOut = FALSE;
    theApp.m_comicsFont.lfCharSet = ANSI_CHARSET;
    theApp.m_comicsFont.lfOutPrecision = OUT_DEFAULT_PRECIS;
    theApp.m_comicsFont.lfClipPrecision = CLIP_DEFAULT_PRECIS;
    theApp.m_comicsFont.lfQuality = DEFAULT_QUALITY;
    theApp.m_comicsFont.lfPitchAndFamily = DEFAULT_PITCH | FF_DONTCARE;
    strcpy(theApp.m_comicsFont.lfFaceName, "Comic Sans MS");
    theApp.m_iFontHeightBalloon = fontHeight;
    theApp.m_comicsColor = RGB(0, 0, 0);
    theApp.m_textColor = RGB(0, 0, 0);
    theApp.m_charSet = ANSI_CHARSET;
    theApp.m_bComicView = TRUE;
    theApp.m_bNoRefresh = TRUE;  // suppress view refresh calls
    theApp.m_flags1 = (DWORD)~0; // all flags on (incl F1_RTFCOMIC)
    theApp.m_bIconMembers = TRUE;
    strcpy(theApp.m_szGuiFaceName, "Comic Sans MS");

    // Create the panel fonts
    CUnitPanelPage::SetFonts(theApp.m_comicsFont, theApp.m_comicsColor);
    fprintf(stderr, "ORACLE: fonts set\n");

    // Set art directory to the tree's ComicArt folder.
    // SetArtDir (protsupp.cpp:164) constructs the avatar/backdrop dir as
    //   m_strBaseDir + "\\" + m_strDefaultArtDir
    // so m_strDefaultArtDir must be a RELATIVE name ("ComicArt"), not a full
    // path, and m_strBaseDir must be the tree root. Using a full path here
    // made SetArtDir double-join the path, so avatar loading failed for every
    // corpus case except the one using treeDir="." (which collapsed via ".").
    theApp.m_strBaseDir = treeDir;
    theApp.m_strDefaultArtDir = "ComicArt";
    // Initialize the avatar/backdrop dirs to match (SetArtDir will be called
    // again by InitMyDocument, but InitializeBackDrops below reads them).
    theApp.m_strBackDropDir = CString(treeDir) + "\\ComicArt";
    theApp.m_strAvatarDir = theApp.m_strBackDropDir;
#ifdef ORACLE_HARNESS
    fprintf(stderr, "ORACLE: treeDir=%s artDir=%s\n", treeDir, (const char*)theApp.m_strAvatarDir);
#endif

    // Initialize backdrops
    InitializeBackDrops();
    fprintf(stderr, "ORACLE: backdrops initialized\n");

    // Load emotion rules (textpose.cpp)
    LoadEmotionStrings();
    InitializeEmotionRules();
    fprintf(stderr, "ORACLE: emotion rules initialized\n");

    // Initialize avatar registry
    InitializeAvatars();
    fprintf(stderr, "ORACLE: avatars initialized\n");
}

// ---------------------------------------------------------------------------
// Load an avatar by name and return its ID.
// In the real app, GetAvatar3(avName, pui) associates each avatar with a
// CUserInfo (so EvalPair/AddTalkTos can deref av->m_userInfo->m_udi.m_talkTos).
// The harness uses LoadAvatar directly, so we must synthesize a CUserInfo per
// avatar and attach it. The userInfoList keeps the CUserInfo objects alive
// for the document's lifetime.
// ---------------------------------------------------------------------------
static CPtrList userInfoList;

static CAvatarX* LoadAvatarNoThrow(const char* name) {
#ifdef _MSC_VER
    CAvatarX* av = NULL;
    __try {
        av = LoadAvatar(name);
    } __except(EXCEPTION_EXECUTE_HANDLER) {
        av = NULL;
    }
    return av;
#else
    // No SEH on clang, so an access violation inside the loader becomes a real crash
    // instead of a NULL return. That is the honest behaviour rather than a silent
    // platform difference - and the Windows harness is where to diagnose which avatar
    // did it. Same treatment as the guards in avbdump.cpp.
    return LoadAvatar(name);
#endif
}

static USHORT LoadAvatarByName(const char* name) {
    fprintf(stderr, "ORACLE: loading avatar '%s'\n", name);
    fflush(stderr);
    CAvatarX* av = LoadAvatarNoThrow(name);
    if (!av) {
        fprintf(stderr, "ORACLE: failed to load avatar '%s'\n", name);
        return 0;
    }
    // Synthesize a CUserInfo so panel ordering (EvalPair/AddTalkTos) can
    // dereference av->m_userInfo->m_udi.m_talkTos without crashing. The talkTos
    // list stays empty (no talk-to targets), which is the correct neutral
    // state for the corpus (messages with talk-tos are a separate case).
    CUserInfo* pui = new CUserInfo();
    pui->SetAvatarID(av->m_avatarID);
    pui->SetName(name);
    av->m_userInfo = pui;
    userInfoList.AddTail(pui);
    fprintf(stderr, "ORACLE: avatar '%s' loaded as ID %d (pui=%p)\n",
            name, av->m_avatarID, (void*)pui);
    return av->m_avatarID;
}

// ---------------------------------------------------------------------------
// Main: replay inputs.json -> expected.json
// ---------------------------------------------------------------------------
int main(int argc, char** argv) {
    // Parse args
    if (argc < 2) {
        fprintf(stderr, "usage: OracleHarness.exe <inputs.json> <expected.json>\n");
        fprintf(stderr, "       OracleHarness.exe --glyphs <glyphs.json>\n");
        fprintf(stderr, "       OracleHarness.exe --codecs <codecs.json>\n");
        fprintf(stderr, "       OracleHarness.exe --ccc <ccc.json> [treeDir]\n");
        fprintf(stderr, "       OracleHarness.exe --avb <outDir> [artDir]\n");
        return 2;
    }

    // Determine tree directory (parent of the harness exe, or from inputs)
    // Default: ".." relative to CWD (CI runs from v2.5-beta-1-modern\)
    char treeDir[MAX_PATH] = "..";
    // Also try exe-relative path as fallback
    char exeDir[MAX_PATH];
    GetModuleFileName(NULL, exeDir, MAX_PATH);
    char* slash = strrchr(exeDir, '\\');
    if (slash) {
        *slash = 0;  // exeDir = Release/
        slash = strrchr(exeDir, '\\');
        if (slash) {
            *slash = 0;  // exeDir = v2.5-beta-1-modern/
            // If the directory exists, use it; otherwise keep ".."
            char testPath[MAX_PATH];
            snprintf(testPath, MAX_PATH, "%s\\ComicArt", exeDir);
            if (GetFileAttributes(testPath) != (DWORD)-1) {
                strcpy(treeDir, exeDir);
            }
        }
    }

    // Glyph capture mode
    if (strcmp(argv[1], "--glyphs") == 0) {
        if (argc < 3) {
            fprintf(stderr, "usage: OracleHarness.exe --glyphs <glyphs.json>\n");
            return 2;
        }
        AfxWinInit(GetModuleHandle(NULL), NULL, ::GetCommandLine(), SW_HIDE);
        if (!cui.m_pvClientDC) {
            CClientDC* dc = new CClientDC(CWnd::FromHandle(::GetDesktopWindow()));
            dc->SetMapMode(MM_TWIPS);
            cui.m_pvClientDC = dc;
        }
        ojson::Value glyphs = CaptureGlyphs();
        FILE* f = fopen(argv[2], "wb");
        if (!f) { fprintf(stderr, "cannot write %s\n", argv[2]); return 1; }
        std::string out = glyphs.EmitToString();
        fwrite(out.c_str(), 1, out.size(), f);
        fclose(f);
        printf("glyphs written to %s\n", argv[2]);
        return 0;
    }

    // Textpose capture mode (Tier-1 #1 dump for the TS port's golden)
    if (strcmp(argv[1], "--textpose") == 0) {
        if (argc < 3) {
            fprintf(stderr, "usage: OracleHarness.exe --textpose <textpose.json>\n");
            return 2;
        }
        AfxWinInit(GetModuleHandle(NULL), NULL, ::GetCommandLine(), SW_HIDE);
        // Textpose doesn't need a DC, but InitializeEmotionRules calls
        // LoadString which needs the resource instance (AfxWinInit handles it).
        LoadEmotionStrings();
        InitializeEmotionRules();
        ojson::Value tp = CaptureTextpose();
        FILE* f = fopen(argv[2], "wb");
        if (!f) { fprintf(stderr, "cannot write %s\n", argv[2]); return 1; }
        std::string out = tp.EmitToString();
        fwrite(out.c_str(), 1, out.size(), f);
        fclose(f);
        printf("textpose written to %s\n", argv[2]);
        return 0;
    }

    // Avatario capture mode (Tier-1 #3 dump: emotion quantization round-trip).
    // Pure-logic, no DC or avatar loading needed — just the avatario module.
    if (strcmp(argv[1], "--avatario") == 0) {
        if (argc < 3) {
            fprintf(stderr, "usage: OracleHarness.exe --avatario <avatario.json>\n");
            return 2;
        }
        AfxWinInit(GetModuleHandle(NULL), NULL, ::GetCommandLine(), SW_HIDE);
        ojson::Value av = CaptureAvatario();
        FILE* f = fopen(argv[2], "wb");
        if (!f) { fprintf(stderr, "cannot write %s\n", argv[2]); return 1; }
        std::string out = av.EmitToString();
        fwrite(out.c_str(), 1, out.size(), f);
        fclose(f);
        printf("avatario written to %s\n", argv[2]);
        return 0;
    }

    // Avatar-pose capture mode (Tier-1 #2 dump: emotion-to-pose selection on
    // synthetic avatars). No DC, no avatar loading, no chatdoc — just the
    // GetBodyFromEmotion nearest-neighbor logic exercised on known input.
    if (strcmp(argv[1], "--avatar-pose") == 0) {
        if (argc < 3) {
            fprintf(stderr, "usage: OracleHarness.exe --avatar-pose <avatar.json>\n");
            return 2;
        }
        AfxWinInit(GetModuleHandle(NULL), NULL, ::GetCommandLine(), SW_HIDE);
        ojson::Value av = CaptureAvatarPose();
        FILE* f = fopen(argv[2], "wb");
        if (!f) { fprintf(stderr, "cannot write %s\n", argv[2]); return 1; }
        std::string out = av.EmitToString();
        fwrite(out.c_str(), 1, out.size(), f);
        fclose(f);
        printf("avatar-pose written to %s\n", argv[2]);
        return 0;
    }

    // Stateless codec capture (Tier-1 #6, #7, #8, #9, #12). Needs AfxWinInit
    // for CString/CDWordArray/CStringArray, but no DC, avatars, or document.
    if (strcmp(argv[1], "--codecs") == 0) {
        if (argc < 3) {
            fprintf(stderr, "usage: OracleHarness.exe --codecs <codecs.json>\n");
            return 2;
        }
        AfxWinInit(GetModuleHandle(NULL), NULL, ::GetCommandLine(), SW_HIDE);
        ojson::Value cx = CaptureCodecs();
        FILE* f = fopen(argv[2], "wb");
        if (!f) { fprintf(stderr, "cannot write %s\n", argv[2]); return 1; }
        std::string out = cx.EmitToString();
        fwrite(out.c_str(), 1, out.size(), f);
        fclose(f);
        printf("codecs written to %s\n", argv[2]);
        return 0;
    }

    // .ccc transcript codec capture (Tier-1 #10). Needs more setup than
    // --codecs: the parse constructors want a CChatDoc for LookupPui. It is a
    // bare doc though - no InitMyDocument, since pages and panels play no part
    // in serialising a history entry.
    if (strcmp(argv[1], "--ccc") == 0) {
        if (argc < 3) {
            fprintf(stderr, "usage: OracleHarness.exe --ccc <ccc.json> [treeDir]\n");
            return 2;
        }
        char treeDir[MAX_PATH] = ".";
        if (argc >= 4) {
            strncpy(treeDir, argv[3], MAX_PATH - 1);
            treeDir[MAX_PATH - 1] = 0;
        }
        InitHarness(treeDir);
        COracleChatDoc* doc = new COracleChatDoc();
        cui.m_pvChatDoc = doc;
        doc->m_view = NULL;
        doc->m_bComicView = TRUE;
        doc->SetComicsTitle("Oracle Comic");
        fprintf(stderr, "ORACLE: ccc - bare doc ready\n"); fflush(stderr);

        ojson::Value cc = CaptureCcc(doc);
        FILE* f = fopen(argv[2], "wb");
        if (!f) { fprintf(stderr, "cannot write %s\n", argv[2]); return 1; }
        std::string out = cc.EmitToString();
        fwrite(out.c_str(), 1, out.size(), f);
        fclose(f);
        printf("ccc written to %s\n", argv[2]);
        return 0;
    }

    // Tier-2: .avb/.bgb asset manifests + decoded-pixel CRC32s. Needs less
    // setup than any other mode - avbfile.cpp and dib.cpp reference theApp only
    // for the #include, never for state, so there is no DC, no font, no emotion
    // table and no avatar registry here. Keeping it that way is the point: the
    // dump then cannot be perturbed by anything outside the two files under
    // test. Writes one manifest per asset plus an index.
    if (strcmp(argv[1], "--avb") == 0) {
        if (argc < 3) {
            fprintf(stderr, "usage: OracleHarness.exe --avb <outDir> [artDir]\n");
            return 2;
        }
        const char* outDir = argv[2];
        char artDir[MAX_PATH];
        if (argc >= 4) {
            strncpy(artDir, argv[3], MAX_PATH - 1);
            artDir[MAX_PATH - 1] = 0;
        } else {
            snprintf(artDir, MAX_PATH, "%s\\ComicArt", treeDir);
        }
        AfxWinInit(GetModuleHandle(NULL), NULL, ::GetCommandLine(), SW_HIDE);

        ojson::Value idx = CaptureAvb(artDir, outDir);
        char idxPath[MAX_PATH];
        snprintf(idxPath, MAX_PATH, "%s\\index.json", outDir);
        FILE* f = fopen(idxPath, "wb");
        if (!f) { fprintf(stderr, "cannot write %s\n", idxPath); return 1; }
        std::string out = idx.EmitToString();
        fwrite(out.c_str(), 1, out.size(), f);
        fclose(f);
        printf("avb manifests written to %s\n", outDir);
        return 0;
    }

    // Normal replay mode
    if (argc < 3) {
        fprintf(stderr, "usage: OracleHarness.exe <inputs.json> <expected.json>\n");
        return 2;
    }

    const char* inputsPath = argv[1];
    const char* expectedPath = argv[2];

    // Read inputs.json
    FILE* fin = fopen(inputsPath, "rb");
    if (!fin) { fprintf(stderr, "cannot open %s\n", inputsPath); return 1; }
    fseek(fin, 0, SEEK_END);
    long sz = ftell(fin);
    fseek(fin, 0, SEEK_SET);
    std::string inputsText(sz, '\0');
    fread(&inputsText[0], 1, sz, fin);
    fclose(fin);

    ojson::Value inputs;
    std::string parseErr;
    if (!ojson::Parse(inputsText, inputs, parseErr)) {
        fprintf(stderr, "parse error in %s: %s\n", inputsPath, parseErr.c_str());
        return 1;
    }

    // Read seed and config
    unsigned int seed = (unsigned int)inputs.GetInt("seed", 42);
    unsigned int tickBase = (unsigned int)inputs.GetInt("tickSeedBase", 1000);
    int panelsWide = (int)inputs.GetInt("panelsWide", 2);
    std::string treeDirFromInputStr = inputs.GetStr("treeDir", "");
    const char* treeDirFromInput = treeDirFromInputStr.c_str();
    if (treeDirFromInput[0]) {
        strncpy(treeDir, treeDirFromInput, MAX_PATH - 1);
        treeDir[MAX_PATH - 1] = 0;
    }

    // Initialize the harness environment
    InitHarness(treeDir);
    fprintf(stderr, "ORACLE: InitHarness complete\n");

    // Panel dimensions already set in InitHarness (before SetFonts)
    CUnitPanelPage::SetUnitPanelsPerRow(panelsWide);  // override from inputs

    // panelsWide alone only sets panels-per-row here: the real client sizes the
    // panel via CPageView::SetPanelsWide -> GetProspectivePanelWidth, which
    // needs a window. So a narrow panel was unreachable from the corpus, and
    // with it the avatar-overflow branch in LayoutAvatars (sumWidth >
    // m_unitWidth) - measured as never taken across all 267 panels. This knob
    // makes panel geometry an explicit corpus input; MINUNITPANELWIDTH (2300)
    // is the floor the real SetPanelsWide clamps to, so values below it would
    // not be reachable in the app either.
    // Width and height are separate knobs on purpose. Bodies are scaled to
    // maxBodyHeight = m_unitHeight / 1.9 (panel.cpp:755) and their widths scale
    // with that ratio, so shrinking width and height together shrinks the
    // avatars just as much and sumWidth can never overtake m_unitWidth - which
    // is why a square 2300 panel still reported reduction 1.0. A narrow *tall*
    // panel is what overflows: full-height bodies in a narrow frame.
    int panelWidth = (int)inputs.GetInt("panelWidth", 4860);
    int panelHeight = (int)inputs.GetInt("panelHeight", 4860);
    if (panelWidth < MINUNITPANELWIDTH || panelHeight < MINUNITPANELHEIGHT) {
        fprintf(stderr, "ORACLE: panel %dx%d is below the MINUNITPANEL floor %dx%d\n",
                panelWidth, panelHeight, MINUNITPANELWIDTH, MINUNITPANELHEIGHT);
        return 2;
    }
    if (panelWidth != 4860 || panelHeight != 4860) {
        CUnitPanelPage::SetUnitPanelWidth(panelWidth);
        CUnitPanelPage::SetUnitPanelHeight(panelHeight);
        fprintf(stderr, "ORACLE: panel geometry overridden to %dx%d\n", panelWidth, panelHeight);
    }

    // Activate the oracle determinism layer
    OracleSeedActivate(seed, tickBase);
    fprintf(stderr, "ORACLE: seed activated (seed=%u, tickBase=%u)\n", seed, tickBase);

    // Load avatars from the inputs
    ojson::Value* avatars = inputs.Find("avatars");
    fprintf(stderr, "ORACLE: loading avatars (avatars=%p, type=%d)\n", (void*)avatars, avatars ? avatars->type : -1);

    fprintf(stderr, "ORACLE: creating CChatDoc...\n");
    // Create the document
    COracleChatDoc* doc = new COracleChatDoc();
    fprintf(stderr, "ORACLE: CChatDoc created\n");
    cui.m_pvChatDoc = doc;  // GetChatDoc() macro will find it

    // m_view is not initialized by CChatDoc ctor — set to NULL so
    // RefreshPanelN's ORACLE_HARNESS guard skips UpdateViewsX
    doc->m_view = NULL;

    // Set comics view mode
    doc->m_bComicView = TRUE;

    // Pre-set a fixed title so GetComicsTitle() doesn't call GetRandomTitle()
    // (which needs string resources the console exe doesn't have)
    doc->SetComicsTitle("Oracle Comic");

    fprintf(stderr, "ORACLE: calling InitMyDocument...\n");
    // Initialize the document (creates first page, seeds the PRNG)
    doc->InitMyDocument();
    fprintf(stderr, "ORACLE: InitMyDocument complete\n");
    fflush(stderr);

    // Load avatars and assign to speakers
    fprintf(stderr, "ORACLE: setting up speaker map\n");
    fflush(stderr);

    // Load avatars and assign to speakers
    // inputs.avatars: array of {name, speakerId}
    // We load each avatar and map speakerId -> avatarID
    struct SpeakerAv { int speakerId; USHORT avatarID; };
    SpeakerAv speakerMap[64];
    int nSpeakers = 0;

    if (avatars && avatars->type == ojson::T_ARRAY) {
        for (size_t i = 0; i < avatars->arr.size(); i++) {
            ojson::Value& a = avatars->arr[i];
            std::string nameStr = a.GetStr("name", "");
            const char* name = nameStr.c_str();
            int speakerId = (int)a.GetInt("speakerId", (long)i);
            if (nSpeakers < 64) {
                USHORT avID = LoadAvatarByName(name);
                speakerMap[nSpeakers].speakerId = speakerId;
                speakerMap[nSpeakers].avatarID = avID;
                nSpeakers++;
            }
        }
    }

    // If no avatars specified, load a default
    if (nSpeakers == 0) {
        USHORT avID = LoadAvatarByName("bolo");
        speakerMap[0].speakerId = 1;
        speakerMap[0].avatarID = avID;
        nSpeakers = 1;
    }

    // Set my avatar to the first one
    if (nSpeakers > 0) {
        doc->m_myAvatarID = speakerMap[0].avatarID;
    }
    fprintf(stderr, "ORACLE: myAvatarID = %d, nSpeakers = %d\n", doc->m_myAvatarID, nSpeakers);
    fflush(stderr);

    // Replay messages
    ojson::Value* messages = inputs.Find("messages");
    ojson::Value dumpRoot = ojson::Value::Obj();
    ojson::Value perMessageDumps = ojson::Value::Arr();
    fprintf(stderr, "ORACLE: messages = %p, type = %d, count = %d\n", (void*)messages, messages ? messages->type : -1, messages ? (int)messages->arr.size() : 0);
    fflush(stderr);

    // Mode constants (from protsupp.h / chatprot.h)
    // BM_SAY=0, BM_WHISPER=1, BM_THINK=2, BM_ACTION=4
    // These map to the uModes parameter of ProcessLine

    if (messages && messages->type == ojson::T_ARRAY) {
        for (size_t i = 0; i < messages->arr.size(); i++) {
            ojson::Value& msg = messages->arr[i];
            int speakerId = (int)msg.GetInt("speakerId", 1);
            std::string textStr = msg.GetStr("text", "");
            const char* text = textStr.c_str();
            int mode = (int)msg.GetInt("mode", 0); // 0=say, 1=whisper, 2=think, 4=action
            int bbCooked = (int)msg.GetInt("bbCooked", 1);

            // Find avatarID for this speaker
            USHORT avatarID = 0;
            for (int s = 0; s < nSpeakers; s++) {
                if (speakerMap[s].speakerId == speakerId) {
                    avatarID = speakerMap[s].avatarID;
                    break;
                }
            }
            if (!avatarID && nSpeakers > 0) {
                avatarID = speakerMap[0].avatarID;
            }

            // Process the line through the engine
            fprintf(stderr, "ORACLE: ProcessLine(avID=%d, text='%s', mode=%d)\n", avatarID, text, mode);
            fflush(stderr);
            doc->ProcessLine(avatarID, text, (USHORT)mode, (BYTE)bbCooked, NULL);
            fprintf(stderr, "ORACLE: ProcessLine done\n");
            fflush(stderr);

            // Dump state after this message
            ojson::Value msgDump = ojson::Value::Obj();
            msgDump.Set("messageIndex", ojson::Value::Int((long)i));
            msgDump.Set("speakerId", ojson::Value::Int(speakerId));
            msgDump.Set("text", ojson::Value::Str(text));
            msgDump.Set("mode", ojson::Value::Int(mode));

            // Dump the current page (tail of m_pages is the newest; head is
            // actually the newest per AddNewPage which does AddHead... but
            // the engine's AddLine uses GetTail which is the oldest page.
            // Wait: AddNewPage does m_pages.AddHead, and AddLine uses
            // m_pages.GetTail() -- so the first page is at the tail.
            // The "current" page being written to is the tail.)
            CPage* currentPage = (CPage*)doc->m_pages.GetTail();
            if (currentPage) {
                msgDump.Set("page", DumpPage(currentPage));
            }

            // Dump all pages (for multi-panel pagination tracking)
            ojson::Value allPages = ojson::Value::Arr();
            POSITION ppos = doc->m_pages.GetHeadPosition();
            while (ppos) {
                CPage* p = (CPage*)doc->m_pages.GetNext(ppos);
                allPages.Push(DumpPage(p));
            }
            msgDump.Set("allPages", allPages);

            // Dump avatar states for all speakers
            ojson::Value avStates = ojson::Value::Obj();
            for (int s = 0; s < nSpeakers; s++) {
                char key[32];
                snprintf(key, sizeof(key), "%d", speakerMap[s].speakerId);
                avStates.Set(key, DumpAvatarState(speakerMap[s].avatarID));
            }
            msgDump.Set("avatarStates", avStates);

            perMessageDumps.Push(msgDump);
        }
    }

    dumpRoot.Set("seed", ojson::Value::Int((long)seed));
    dumpRoot.Set("tickSeedBase", ojson::Value::Int((long)tickBase));
    dumpRoot.Set("panelsWide", ojson::Value::Int(panelsWide));
    // Record the geometry the run actually used, not just what was requested -
    // every world-unit coordinate below is relative to it.
    dumpRoot.Set("panelWidth", ojson::Value::Int(CUnitPanelPage::m_unitWidth));
    dumpRoot.Set("panelHeight", ojson::Value::Int(CUnitPanelPage::m_unitHeight));
    dumpRoot.Set("messages", perMessageDumps);

    // Dump seed ledger (Phase 0 determinism verification)
    dumpRoot.Set("seedLedger", DumpSeedLedger());

    // Dump font info for this run
    ojson::Value fontInfo = ojson::Value::Obj();
    fontInfo.Set("faceName", ojson::Value::Str("Comic Sans MS"));
    fontInfo.Set("lfHeight", ojson::Value::Int(theApp.m_iFontHeightBalloon));
    fontInfo.Set("charSet", ojson::Value::Int(ANSI_CHARSET));
    dumpRoot.Set("fontConfig", fontInfo);

    // Write expected.json
    std::string out = dumpRoot.EmitToString();
    FILE* fout = fopen(expectedPath, "wb");
    if (!fout) { fprintf(stderr, "cannot write %s\n", expectedPath); return 1; }
    fwrite(out.c_str(), 1, out.size(), fout);
    fclose(fout);

    printf("oracle dump written to %s (%d messages)\n",
           expectedPath, (int)perMessageDumps.arr.size());

    // Cleanup
    delete doc;

    return 0;
}